Issue1037 assignment polls sort by vote number
OpenSlides/openslides-client pull request #1050
Opened 2022-05-03 09:15 UTC by luisa-beerboom

Closes #1037 
Changed table-data-generation to treat undocumented optional values as if they were 0.

2022-05-03 20:22 UTC, emanuelschuetze approved these changes
Successfully tested. - But prettify-check still failed.

2022-05-05 15:48 UTC, GabrielInTheWorld requested changes

2022-05-05 15:48 UTC, GabrielInTheWorld commented on client/src/app/site/polls/services/poll.service.ts
> +    }
Please make it a more re-usable/generic function and extract it into an own file.

2022-05-06 08:49 UTC, luisa-beerboom commented
Old version, see #1076 for new one

2022-05-06 08:49 UTC, closed without merging