Include the motion attachment in the PDF export
OpenSlides/openslides-client pull request #1052
Opened 2022-05-03 11:01 UTC by m-schieder

* This can be switched on and off via the pdf export dialog.

2022-05-03 20:27 UTC, emanuelschuetze requested changes
images works good.
for other files: we have to print the full attachment url into pdf (a link is not useable in a printed motion book)

2022-05-04 12:37 UTC, m-schieder commented
Feedback on exactly what the output should look like should come tomorrow.

2022-05-07 15:14 UTC, emanuelschuetze approved these changes

2022-05-07 15:15 UTC, emanuelschuetze commented
Please resolve all conflicts.

2022-05-10 06:57 UTC, GabrielInTheWorld requested changes
Please rebase and check my comments.

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/core/pdf-services/pdf-document.service.ts
> +    public mmToPoints(mm: number): number {
This is already a utitlity function, which can be imported. So, remove it here.

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/motions/services/motion-pdf.service.ts
> +    private PDF_A5_POINTS_WIDTH = 419.53;
Some remarks here:

- Could you please describe, how the numbers were calculated?
- Either mark them as `readonly` or (my preference) extract them as constants to the top of the file

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/motions/services/motion-pdf.service.ts
> +        const pageSize = this.meetingSettingsService.instant(`export_pdf_pagesize`);
could you extract these constants as getters?

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/motions/services/motion-pdf.service.ts
> +        });
Should this always be appended or only when at least one attachment is exported?

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/motions/services/motion-pdf.service.ts
> +            if (attachment.isImageUsableForPdf()) {
You should put the function `isImageUsableForPdf` into this file or even better into the new `PdfImageService`.

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/motions/services/motion-pdf.service.ts
> +            }
Please create a function for that like `createPdfImage` or something else.

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/mediafiles/models/view-mediafile.ts
> +export const IMAGE_USABLE_FOR_PDF_MIMETYPES = [`image/png`, `image/jpeg`];
I think, this is a too specific declaration, see the `MotionPdfService` for hints

2022-05-10 06:57 UTC, GabrielInTheWorld commented on client/src/app/site/mediafiles/models/view-mediafile.ts
> +
Same as above.

2022-05-11 12:56 UTC, GabrielInTheWorld approved these changes
Two remarks, but the rest looks good! You can merge, after you resolved the remarks.

2022-05-11 12:56 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
> +            debugger;
I _think_ this can be removed

2022-05-11 12:56 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
> + * A5: 5.827 x 72 = 419.544
Can you give a hint, why `8.268` respectively `5.827`?

2022-05-11 14:30 UTC, merged