Can now open fullscreen from autopilot
OpenSlides/openslides-client pull request #1054
Opened 2022-05-03 12:15 UTC by luisa-beerboom

Closes #1042 
Found out that the link in the cinema component was broken and proceeded to replace it with the working one from the projector-list-entry component.

2022-05-03 12:57 UTC, GabrielInTheWorld approved these changes

2022-05-03 20:35 UTC, emanuelschuetze requested changes
Open projector works now from autopilot.
But if you go to main menu entry "Projector" and opens (as delegate user) the projector by click you get a black page...

2022-05-04 10:42 UTC, emanuelschuetze approved these changes

2022-05-05 15:45 UTC, GabrielInTheWorld requested changes

2022-05-05 15:45 UTC, GabrielInTheWorld commented on client/src/app/site/projector/components/projector-list-entry/projector-list-entry.component.ts
> +            return `/${this.activeMeetingId}/projector/${this.projector.id}`;
Will this still work? Please check!

2022-05-06 14:47 UTC, luisa-beerboom commented
Currently not functional:
Links should open a new tab with the fullscreen projector, but instead the new tab contains the calendar with the url:
https://localhost:8000/?error=Authentication%20Error&msg=meeting.can_see_frontpage

Probably related to issue #1080

2022-05-10 06:59 UTC, GabrielInTheWorld commented
> Currently not functional: Links should open a new tab with the fullscreen projector, but instead the new tab contains the calendar with the url: https://localhost:8000/?error=Authentication%20Error&msg=meeting.can_see_frontpage
> 
> Probably related to issue #1080

A projector should be requested by its `sequential_number`. Please try this and give me a feedback, if its still not work.

2022-05-10 11:51 UTC, luisa-beerboom commented
> > Currently not functional: Links should open a new tab with the fullscreen projector, but instead the new tab contains the calendar with the url: https://localhost:8000/?error=Authentication%20Error&msg=meeting.can_see_frontpage
> > Probably related to issue #1080
> 
> A projector should be requested by its `sequential_number`. Please try this and give me a feedback, if its still not work.

The reason I currently request it by it's id, instead of the sequential number, is bc these were the correct and working routes to the fullscreen-page before the rebase to the new version. Unless the Angular 13 update changed the routes, they therefore still should be correct.
Just for the sake of being safe I _did_ try out the `sequential_number`-routes too, those also didn't work and, as far as I remember, instead routed to the default route, not 100% sure on that, I will try it again later.

2022-05-17 21:42 UTC, emanuelschuetze approved these changes

2022-05-17 21:42 UTC, merged