Fixed link in login-wrapper
OpenSlides/openslides-client pull request #1057
Opened 2022-05-03 13:32 UTC by luisa-beerboom

Closes #800 
Router link in reset-password.html contained meeting id when it shouldn't have
Link in login-wrapper didn't have a path

2022-05-03 20:46 UTC, emanuelschuetze requested changes
Your fix works for reset-password-back-link. But we need also a solution for legalnotice and privacypolicy to close the issue.

2022-05-04 10:39 UTC, emanuelschuetze approved these changes

2022-05-05 11:51 UTC, GabrielInTheWorld commented on client/src/app/site/login/components/reset-password/reset-password.component.html
> +        <button type="button" mat-button [routerLink]="['/login']">
Pay attention to #1048

2022-05-05 11:52 UTC, GabrielInTheWorld approved these changes

2022-05-05 15:54 UTC, merged