Assignment poll results now sorted correctly
OpenSlides/openslides-client pull request #1076
Opened 2022-05-06 08:46 UTC by luisa-beerboom

Closes #1037 
Changed table-data-generation to treat undocumented optional values as if they were 0.

2022-05-06 08:48 UTC, luisa-beerboom commented
Basically same content as #1050 but requested changes were applied and it was rebased to current client

2022-05-07 12:34 UTC, emanuelschuetze approved these changes

2022-05-10 06:35 UTC, GabrielInTheWorld requested changes

2022-05-10 06:35 UTC, GabrielInTheWorld commented on client/src/app/infrastructure/utils/functions.ts
> +export function compareValues(a: number, b: number): number {
If you only compare numbers, please name it something like `compareNumber` or add this function to the `Number` namespace (my preference). To do the second one, you should check the file `overload-js-functions.ts`.

2022-05-10 07:20 UTC, GabrielInTheWorld approved these changes

2022-05-10 11:58 UTC, merged