Search bar now filters by sequential number instead of id
OpenSlides/openslides-client pull request #1119
Opened 2022-05-16 14:27 UTC by luisa-beerboom

2022-05-16 15:52 UTC, GabrielInTheWorld requested changes

2022-05-16 15:52 UTC, GabrielInTheWorld commented on client/src/app/ui/modules/list/components/list/list.component.ts
> -            const idString = `` + item.id;
Pay attention here: Keep in mind, that there are models without a `sequential_number`

2022-05-18 07:58 UTC, GabrielInTheWorld approved these changes
It is okay for me. I'm still not quite comfortable with the name. Maybe we can change it someday.

2022-05-18 09:22 UTC, GabrielInTheWorld commented
@emanuelschuetze: These changes work fine. Feel free to merge this PR.

2022-05-18 11:33 UTC, emanuelschuetze approved these changes

2022-05-18 11:33 UTC, merged