Refactored FilterListService
OpenSlides/openslides-client pull request #1158
Opened 2022-05-19 10:51 UTC by luisa-beerboom

Closes #1137

2022-05-19 12:47 UTC, GabrielInTheWorld requested changes
I haven't reviewed every yet, but there are already some things which should be changed.

2022-05-19 12:47 UTC, GabrielInTheWorld commented on client/src/app/ui/base/filter-service.ts
> +export class FilterListData<V>{
The implementation of `FilterListData` should implement the interface.

2022-05-19 12:47 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/base/base-meeting-filter-list.service.ts
> +        });
This is duplicated code from the `BaseFilterListService`

2022-05-19 12:47 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/base/base-meeting-filter-list.service.ts
> +    // protected abstract readonly storageKey: string;
Remove

2022-05-19 12:47 UTC, GabrielInTheWorld commented on client/src/app/site/base/base-filter.service/base-filter-list.service.ts
> +        this.filterListData = new FilterListData<V>();
The idea behind the creating of an instance of `FilterListData` was not to just use it as data wrapper. Instead, please implement a real `create` or `build` function, which returns an instance of `FilterListData`. The `FilterListData` instance should then provide every function, which works on its data. The `BaseFilterListService` should provide functions, which filters a source by given `FilterDefinition`s.

2022-05-20 10:04 UTC, luisa-beerboom commented
More recent and practical solution in #1162

2022-05-20 10:04 UTC, closed without merging