Implemented default projector selection
OpenSlides/openslides-client pull request #1277
Opened 2022-06-15 09:44 UTC by luisa-beerboom

Closes #1062

2022-06-15 12:25 UTC, GabrielInTheWorld requested changes

2022-06-15 12:25 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.html
> +                    </mat-option>
```suggestion
                    <mat-option *ngFor="let pd of projectionDefaultOptions | keyvalue" [value]="pd.key">
                        {{ pd.value | translate }}
                    </mat-option>
```

2022-06-15 12:25 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
> +    public readonly projectionDefaultOptions = Object.keys(ProjectiondefaultVerbose).map(key => ({
Remove

2022-06-15 12:25 UTC, GabrielInTheWorld commented on client/src/app/site/pages/meetings/pages/projectors/components/projector-edit-dialog/components/projector-edit-dialog/projector-edit-dialog.component.ts
> +    private handleMeeting(meeting: ViewMeeting): void {
```suggestion
    private updateProjectorDefaults(meeting: ViewMeeting): void {
```

2022-06-21 14:58 UTC, emanuelschuetze approved these changes

2022-06-21 21:24 UTC, emanuelschuetze commented
@GabrielInTheWorld Can we merge this?

2022-06-22 10:29 UTC, GabrielInTheWorld approved these changes

2022-06-22 13:21 UTC, merged