Repaired category detail sort
OpenSlides/openslides-client pull request #1317
Opened 2022-06-24 12:48 UTC by luisa-beerboom

Closes #1307

2022-06-27 14:08 UTC, jsangmeister requested changes
looks good besides some debug stuff. Not tested

2022-06-27 14:08 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.ts
> +        console.log(`viewInit`);
remove

2022-06-27 14:08 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.ts
> +
remove

2022-06-27 14:16 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/pages/categories/components/category-detail-sort/category-detail-sort.component.ts
> +
Remove what?

2022-06-29 07:25 UTC, emanuelschuetze requested changes
Create two categories, move one category as subcategory. Add motions to subcategory. Open subcategory detail view => empty, no motions!

2022-06-29 11:54 UTC, emanuelschuetze approved these changes

2022-06-29 11:54 UTC, merged