Implemented AddToMeetingsComponent
OpenSlides/openslides-client pull request #1369
Opened 2022-07-13 13:35 UTC by luisa-beerboom

Closes #1365 

_Should_ work perfectly once OpenSlides/openslides-backend#1403 is merged

2022-07-14 10:25 UTC, jsangmeister requested changes

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
> +        return !!dataLength;
```suggestion
        return Object.values(this.resultsTableDataSubjects).some(subject => subject.value.length);
```
this or something similar would be shorter (not tested)

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.html
> +    </button>
Shouldn't this also be in the container below since it is only executable with OML `can_manage_users`?

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-list/components/account-list/account-list.component.html
> +        </a>
same here, some check should exist so it is not displayed to users without permission (or is this whole view only accessible with the correct OML? then nvm)

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
> +    public isOwnPage = false;
where are these used?

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
> +    }
This looks hacky. Maybe this is not needed (see comment regarding the permission variables above), but if it is, can you transform then into getters and let the change detection handle the updates so these helper functions can be removed?

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
> +        this.assignMeetingsForm.get(`meeting_ids`).reset([]);
I think
```suggestion
        this.assignMeetingsForm.reset({
            group_name: null,
            meeting_ids: [],
        });
```
or similar should also work (but that's maybe a little pedantic :D)

2022-07-14 10:25 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-add-to-meetings/account-add-to-meetings.component.ts
> +        data.forEach(result => {
You can be sure that there is always exactly one result, so you don't need to iterate over the data or do the whole concatenation below, if I understood it right. Just directly mapping ids to names and feeding it into the subject should be enough.

2022-07-15 14:40 UTC, emanuelschuetze approved these changes

2022-07-16 08:39 UTC, jsangmeister approved these changes

2022-07-18 05:58 UTC, merged