Make user lists sort by full name by default
OpenSlides/openslides-client pull request #1443
Opened 2022-07-22 14:03 UTC by luisa-beerboom

Closes #1387

2022-07-25 06:39 UTC, jsangmeister requested changes
Can you give multiple properties to filter for? Full name is still different to first name since it includes title etc. I would like for the "First name" selection to filter by `(first_name, last_name)` to properly display the list.

2022-07-25 06:44 UTC, jsangmeister commented
Okay, looks like the `base-sort.service` does not implement this functionality yet, but you extend https://github.com/OpenSlides/openslides-client/blob/d89313bf3fccbeceaee192977098eb784350ebfe/client/src/app/site/base/base-sort.service/base-sort.service.ts#L46 to be able to handle an array of properties and filter by all of them one after another.

2022-07-25 15:39 UTC, jsangmeister requested changes
Looks very good, except for some (i assume) missed places!

2022-07-25 15:39 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
> +        { property: [`last_name`, `last_name`], label: `Surname` },
```suggestion
        { property: [`last_name`, `first_name`], label: `Surname` },
```
probably you meant this?

2022-07-25 15:39 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-list/services/participant-list-sort.service/participant-list-sort.service.ts
> +            sortProperty: `first_name`,
```suggestion
            sortProperty: [`first_name`, `last_name`],
```

2022-07-25 15:39 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
> +        { property: [`last_name`, `last_name`], label: `Surname` },
same here

2022-07-25 15:39 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/accounts/pages/account-list/services/account-list-sort.service/account-sort.service.ts
> +            sortProperty: `first_name`,
same here

2022-07-26 12:17 UTC, jsangmeister approved these changes

2022-08-02 11:45 UTC, MSoeb approved these changes

2022-08-04 08:03 UTC, merged