[WIP] Now shows meeting time in forwarding dialog
OpenSlides/openslides-client pull request #1489
Opened 2022-08-10 15:19 UTC by luisa-beerboom

Closes #1181 

Currently only works if the meetings have been loaded already, which is suboptimal, because it is possible that the user hasn't loaded them/isn't allowed to load them.

start- and end_time should be added to the `get_forwarding_meetings`-presenter response

2022-08-15 10:45 UTC, jsangmeister requested changes

2022-08-15 10:45 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
> +        console.log(`COMMITTEES: `, result);
remove

2022-08-15 10:45 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
> +    }
I don't think this is used anywhere

2022-08-15 10:45 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
> +                            {{ meeting.end_time | localizedDate: 'll' }}
What happens if start/end time is null? You probably need to wrap it in some container

2022-08-15 13:52 UTC, jsangmeister requested changes

2022-08-15 13:52 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.ts
> +    }
This is not needed either, right?

2022-08-15 13:52 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/components/motion-forward-dialog/components/motion-forward-dialog/motion-forward-dialog.component.html
> +                        <span *ngIf="meeting.start_time && meeting.end_time">
I think it is possible to set just the start or the end time, right? So this should be split to only display one of them

2022-08-16 09:50 UTC, jsangmeister approved these changes

2022-08-23 05:43 UTC, emanuelschuetze requested changes
Please remove the unused star icon in forward dialog.

2022-08-24 15:51 UTC, emanuelschuetze approved these changes

2022-08-24 15:51 UTC, merged