User with OML.can_manage_users can now create accounts
OpenSlides/openslides-client pull request #1492
Opened 2022-08-11 15:20 UTC by luisa-beerboom

...without errors

Closes #984

2022-08-12 07:24 UTC, bastianjoel approved these changes

2022-08-24 15:30 UTC, emanuelschuetze requested changes
Create user (as acconut manager) works. But edit an created user gets same error: `data.committee_$_management_level must be object`

2022-08-25 09:22 UTC, bastianjoel approved these changes

2022-09-01 08:03 UTC, emanuelschuetze approved these changes

2022-09-01 08:03 UTC, merged