[WiP] enable karma tests
OpenSlides/openslides-client pull request #1493
Opened 2022-08-12 11:23 UTC by bastianjoel

resolves #1001

2022-08-15 07:02 UTC, jsangmeister requested changes
Looks very good! Some points:
- Why did you change all `describe`s to `xdescribe`s?
- Some tests are commented out, is this on purpose?
- Can you maybe provide a default configuration for all `TestBed`s automatically where the `E2EImportsModule` is already imported, so that you don't have to do that for all tests where it is needed?

2022-08-15 09:48 UTC, bastianjoel commented
The `x` Infront of `describe` disables a test. 
Most of these disabled tests fail due to not added imports and declarations to the TestBed and because they only created components or services and checked if they were successfully instantiated I decided to disable them. My main goal with this PR is to get the karma test running and add the motion diff tests from OS3. 

Commenting tests out was not on purpose. I will change them to `xdescribe`.

I think adding the `E2EImportsModule` could be done later when we know how many tests actually need it.

2022-08-15 09:50 UTC, jsangmeister commented
> The `x` Infront of `describe` disables a test.

Ah, I confused it with `fdescribe`. Ok, sounds good

2022-08-16 10:10 UTC, jsangmeister approved these changes

2022-08-16 10:54 UTC, merged