Validation of meeting time
OpenSlides/openslides-client pull request #1497
Opened 2022-08-16 11:16 UTC by luisa-beerboom

Closes #1368

2022-08-16 12:10 UTC, jsangmeister approved these changes

2022-08-24 06:56 UTC, emanuelschuetze requested changes
An error message is not really nice... I expected: If I changed the start date, the end date should be set to start date. Than I can save directly (without changing end date) if my meeting is a one-day-event.

2022-08-24 09:28 UTC, luisa-beerboom commented
> An error message is not really nice... I expected: If I changed the start date, the end date should be set to start date. Than I can save directly (without changing end date) if my meeting is a one-day-event.

So in other words: 
If the user changes one date and the result is valid, do nothing further. 
If the user changes one date and the result is invalid, change the other so that they are the same date?

2022-08-25 12:39 UTC, jsangmeister requested changes
I would remove the message completely if we go the way of automatically changing the time and not change the other date upon submition of the form, but as soon as the other date is changed. So, I enter an end date which is earlier than my start date, my start date will automatically be set to the new end date. This will also simplify the code a lot.

2022-08-25 13:44 UTC, jsangmeister approved these changes

2022-08-26 07:50 UTC, emanuelschuetze approved these changes

2022-08-26 07:51 UTC, merged