Changed set state to now open snackbar instead of throwing different …
OpenSlides/openslides-client pull request #1511
Opened 2022-08-18 15:26 UTC by luisa-beerboom

…workflows error

Removed the console error, the text is now being displayed in a snackbar.

2022-08-23 06:33 UTC, jsangmeister requested changes

2022-08-23 06:33 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/components/motion-multiselect/services/motion-multiselect.service.ts
> +            snackBar.open(this.translate.instant(errorMsg), `Ok`);
Can't you just use `this.snackbar`?

2022-08-23 12:12 UTC, jsangmeister approved these changes

2022-08-24 06:33 UTC, emanuelschuetze approved these changes

2022-08-24 06:35 UTC, merged