Made meeting-internal delete use handle separately route
OpenSlides/openslides-client pull request #1524
Opened 2022-08-24 13:35 UTC by luisa-beerboom

Closes #1523 

This solves the problem described in OpenSlides/openslides-backend#1426 where trying to remove multiple participants from a meeting using multiselection would cause datastore broken lock errors when among the selected users the following was true:
There is at least one group that has:
1. At least two selected users
2. Among the selected users of that group there is at least one who is in another meeting, and at least one who is in no other meeting.

2022-08-25 12:32 UTC, jsangmeister requested changes

2022-08-25 12:32 UTC, jsangmeister commented on client/src/app/gateways/actions/action.service.ts
>      public create<T>(...requests: ActionRequest[]): Action<T> {
Can't you just add the optional parameter to this method? I don't see the use of the new `createFromArray` method.

2022-08-25 13:11 UTC, jsangmeister commented on client/src/app/gateways/actions/action.service.ts
>      public create<T>(...requests: ActionRequest[]): Action<T> {
Ah, I see. I can't estimate the time to fix this, but if it's too much, I'm fine with the way it is.

2022-08-25 13:12 UTC, jsangmeister approved these changes

2022-09-01 07:53 UTC, emanuelschuetze approved these changes

2022-09-01 07:53 UTC, merged