[WIP] Beautification of the password reset page
OpenSlides/openslides-client pull request #1526
Opened 2022-08-24 15:17 UTC by luisa-beerboom

Closes #757 

Currently the page will throw an error: `Error when trying to forward to only meeting: Operator has not fully loaded yet.` if one clicks the reset password button.

This is triggered by a navigation command. 
Once I have the information, where that button is supposed to navigate to, I shall fix that and request reviews

2022-11-10 09:45 UTC, luisa-beerboom commented
It should navigate back to login page and open a snackbar like "Es wurde eine E-Mail mit Link zum Passwort-Zurücksetzen gesendet." there

2022-11-11 08:12 UTC, emanuelschuetze requested changes
The forget-password view works now as expected (in issue #757).
But after clicking on email confirm link you see the forget-password-confirm which has broken css...
![password-confirm](https://user-images.githubusercontent.com/2075427/201295622-e69bbf24-0a4b-4ebe-8677-359bcb170f4d.png)

2022-11-11 12:42 UTC, luisa-beerboom commented
> The forget-password view works now as expected (in issue #757). But after clicking on email confirm link you see the forget-password-confirm which has broken css... ![password-confirm](https://user-images.githubusercontent.com/2075427/201295622-e69bbf24-0a4b-4ebe-8677-359bcb170f4d.png)

That looks bad indeed, how do I get to that page in my dev environment?

2022-11-15 07:21 UTC, emanuelschuetze approved these changes

2022-11-15 08:25 UTC, bastianjoel approved these changes

2022-11-15 08:26 UTC, merged