Changed import list to show checkboxes for boolean entries
OpenSlides/openslides-client pull request #1540
Opened 2022-08-29 14:52 UTC by luisa-beerboom

Closes #1527

2022-08-30 06:40 UTC, jsangmeister requested changes

2022-08-30 06:40 UTC, jsangmeister commented on client/src/app/ui/modules/import-list/components/import-list/import-list.component.html
> +    <div *ngIf="entry[def] && type !== 'boolean'" class="flex-vertical-center">
```suggestion
    <div *ngIf="entry[def] || type === 'boolean'" class="flex-vertical-center">
```
and then move the separate div below up into its own `ng-container` to deduplicate the warning icon

2022-08-30 08:38 UTC, jsangmeister approved these changes

2022-09-01 06:54 UTC, emanuelschuetze requested changes
Column 'is present' always show inactive checkboxes! Use a csv with 'is present = 1'. Preview does not show activated checkbox.

2022-09-01 10:47 UTC, emanuelschuetze approved these changes

2022-09-01 10:47 UTC, merged