Made livestream hide when perms are changed
OpenSlides/openslides-client pull request #1553
Opened 2022-09-01 15:29 UTC by luisa-beerboom

Closes #1552

2022-09-05 05:46 UTC, jsangmeister requested changes

2022-09-05 05:46 UTC, jsangmeister commented on client/src/app/site/services/operator.service.ts
> +            console.log(`Groups UPDATED!!!`);
remove

2022-09-05 07:44 UTC, jsangmeister commented
https://github.com/OpenSlides/openslides-client/issues/1439 and https://github.com/OpenSlides/openslides-client/issues/1421 seem similar. Would it be possible to find a generic solution where the operator gets automatically updated when a permission changes and the page updates automatically accordingly?

2022-09-05 10:23 UTC, emanuelschuetze approved these changes

2022-09-12 16:04 UTC, luisa-beerboom commented
> #1439 and #1421 seem similar. Would it be possible to find a generic solution where the operator gets automatically updated when a permission changes and the page updates automatically accordingly?

You're right, and the permission-observable that is introduced in this PR should probably be used as a solution for those, but it should probably still be done in a different PR

2022-09-15 06:39 UTC, jsangmeister approved these changes

2022-09-15 07:17 UTC, merged