[WIP] handle autoupdate via service worker/shared worker
OpenSlides/openslides-client pull request #1556
Opened 2022-09-02 10:06 UTC by bastianjoel

resolves part of #1339

2022-09-14 12:20 UTC, luisa-beerboom requested changes
Some coding style things. I've said most of them only once, please take a look where else they apply. Especially the thing about the return values happens basically everywhere.

2022-09-14 12:20 UTC, luisa-beerboom commented on client/src/app/worker/autoupdate-stream-pool.ts
> +            port.postMessage({
Just put this in the above loop as well

something like:
```
            ...
            ports.push(port)
            port.postMessage({...})
            ...
```

No need to iterate over everything _again_.

Also: The deeply nested for loops make this a bit unreadable, maybe create a helper function.

Also: If you'd prefer not to move postMessage into the big for loop, maybe you could turn the ports-Array into a set?
That way you could skip the explicit duplication check and just use `.add(port)`

2022-09-14 12:20 UTC, luisa-beerboom commented on client/src/app/worker/autoupdate-stream.ts
> +        while (!(result = await reader.read()).done) {
This is too long and too nested. Maybe create helper functions if it makes sense

2022-09-15 13:50 UTC, luisa-beerboom requested changes

2022-09-15 13:50 UTC, luisa-beerboom commented on client/src/app/worker/sw-autoupdate.ts
> +        if (receiver === `autoupdate`) {
Use a switch statement here

2022-09-26 09:13 UTC, luisa-beerboom approved these changes

2022-09-29 15:28 UTC, bastianjoel commented
Switching to draft because there is a authentication problem when opening new tabs

2022-09-30 09:57 UTC, luisa-beerboom approved these changes
Looks good, just one minor remark

2022-09-30 09:57 UTC, luisa-beerboom commented on client/src/app/worker/autoupdate-stream.ts
> +    ): Promise<{ stopReason: 'error' | 'aborted' | 'unused' | 'resolved' | 'in-use'; error?: any }> {
`'error' | 'aborted' | 'unused' | 'resolved' | 'in-use'` looks like you may turn it into a type or an enum or smth

2022-09-30 11:50 UTC, emanuelschuetze approved these changes

2022-09-30 15:23 UTC, merged