Added new filters and sorting options to the account list
OpenSlides/openslides-client pull request #1560
Opened 2022-09-02 14:27 UTC by luisa-beerboom

Closes #1558 

The new sorting options currently can't be tested because of #1559, so that one should be fixed quickly.
After that, the last bugs in this PR can be fixed, or it can be opened for review.

2022-09-05 11:05 UTC, emanuelschuetze commented
new filter successfully tested. Not tested: new sort options -> wait for https://github.com/OpenSlides/openslides-client/issues/1559

2022-09-05 18:25 UTC, emanuelschuetze requested changes
Rebased. New search optoins works now.

2022-09-05 18:25 UTC, emanuelschuetze approved these changes
Rebased. New search optoins works now.

2022-09-06 07:02 UTC, bastianjoel approved these changes

2022-09-06 19:53 UTC, merged