Made JSON file imports show snackbar message
OpenSlides/openslides-client pull request #1585
Opened 2022-09-13 07:21 UTC by luisa-beerboom

Closes #1562

2022-09-13 13:24 UTC, emanuelschuetze approved these changes

2022-09-15 06:47 UTC, jsangmeister requested changes

2022-09-15 06:47 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.ts
> +import { WRONG_JSON_IMPORT_FORMAT_ERROR_MSG } from 'src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-import/workflow-import.component';
Don't cross-import from other components, export it from a common source instead

2022-09-15 06:47 UTC, jsangmeister commented on client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-meeting/components/meeting-import/meeting-import.component.ts
> +                    }
Please move this whole function to a higher level class to deduplicate the code. As far as I see it, the only difference to the code in the workflow import is the used repository, so this should be easy to do.

2022-09-15 12:23 UTC, jsangmeister approved these changes

2022-09-16 05:50 UTC, emanuelschuetze approved these changes

2022-09-16 05:50 UTC, merged