Improve Layout of committee detail view
OpenSlides/openslides-client pull request #1596
Opened 2022-09-14 12:36 UTC by bastianjoel

resolves #1574

2022-09-17 00:14 UTC, tsiegleauq commented on client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
> +            <ul class="content-list expandable-list" [ngClass]="forwardingExpanded ? 'expanded' : ''">
`[class.expanded]="forwardingExpanded"`

2022-09-17 00:29 UTC, tsiegleauq commented on client/src/app/site/pages/organization/pages/committees/pages/committee-detail/modules/committee-detail-view/components/committee-detail-view/committee-detail-view.component.html
> +            <ul class="content-list expandable-list" [ngClass]="receiveExpanded ? 'expanded' : ''">
`[class.expanded]="receiveExpanded"`

2022-09-22 15:29 UTC, emanuelschuetze requested changes
Only the orga admin should see the "Forward motions to"/"Receive motions from" fields because committee admins have not read access for all committees (-> they get an incomplete commitee list which should be prevent).
So please add a new check that orga admins can see only the fields.

2022-09-26 17:56 UTC, emanuelschuetze requested changes
Please order the committes by name (currently it looks like by id which is not helpful)

2022-09-27 15:57 UTC, emanuelschuetze approved these changes

2022-09-27 15:59 UTC, rrenkert approved these changes

2022-09-27 16:04 UTC, merged