fix BaseModelRequestHandlerComponent onParamsChanged not called
OpenSlides/openslides-client pull request #1602
Opened 2022-09-15 12:23 UTC by bastianjoel

resolves #1592

2022-09-15 14:53 UTC, luisa-beerboom requested changes
`onParamsChanged` is a function that is basically only used to open subscriptions when meetings are changed. Expanding it to fire basically whenever there is a new route is therefore probably redundant, especially since you're just seeking to fix one problem, in one single place. Is there no other solution at a lower level that doesn't require the client to try and open new subscriptions on every page change?
Perhaps you're not subscribed to something, or the component watches changes within the viewed motion and therefore, while it will notice changes in the array of forwarded motions, it will not notice anything that goes on within these motions (i.e. new timestamps)

2022-09-22 10:45 UTC, bastianjoel commented
@luisa-beerboom I have looked through the overrides of `onParamsChanged` and saw that most of those methods seem to assume that this is fired whenever a parameter is changed. 
Also there is a `onNextMeetingId` method that should be used to listen for meeting changes. 

I will update the places where `onParamsChanged` is used instead of `onNextMeetingId` and add a parameter to the `onParamsChanged` method that contains the old parameter values.

2022-09-26 07:27 UTC, emanuelschuetze approved these changes

2022-09-26 09:10 UTC, luisa-beerboom approved these changes
Look good, not tested

2022-09-26 11:54 UTC, merged