Restyled 'Add to Meeting'
OpenSlides/openslides-client pull request #1627
Opened 2022-09-28 13:13 UTC by luisa-beerboom

Closes #1623

2022-09-28 14:57 UTC, bastianjoel approved these changes

2022-09-28 20:34 UTC, emanuelschuetze requested changes
* Filter/Search by committee name is not possible (only meeting name works)
* the selected meetings line (in grey) is not useful if you select a lot of meeting (>10). You get a scrollbar. Suggestion: remove selected line, checkboxes are sufficient.
* can you increase the high of meeting select box? currently there is place for 4 lines only...

2022-09-30 07:19 UTC, emanuelschuetze requested changes
more space for result rows

2022-09-30 11:03 UTC, emanuelschuetze approved these changes

2022-09-30 11:18 UTC, merged