cache has voted requests in vote repository
OpenSlides/openslides-client pull request #1662
Opened 2022-10-05 14:44 UTC by bastianjoel

This resolves #1633 by adding a cache and request bundling mechanism to the VoteRepositoryService.

Requested ids from the voted endpoint get cached for 1 second and not cached ids will be collected for 50ms before they will be requested together.

2022-10-05 15:30 UTC, luisa-beerboom approved these changes
Looks fine, but could you maybe look into just reducing unnecessary calls to `VoteControllerService.hasVotedFor`?

That one is the only function that calls this method, and it doesn't exactly return anything. All it does is extract the relevant data from the response and write it into the model.
If it wasn't constantly called with the exact same values, it would probably be better

2022-10-10 05:49 UTC, jsangmeister requested changes

2022-10-10 05:49 UTC, jsangmeister commented on client/src/app/gateways/repositories/polls/vote-repository.service/vote-repository.service.ts
> +        if (ids.some(id => !!result[id])) {
```suggestion
        if (ids.every(id => !!result[id])) {
```
or else you would return potentially incomplete results

2022-10-12 18:04 UTC, emanuelschuetze approved these changes

2022-10-12 18:05 UTC, merged