Participants: Reordered import and export columns
OpenSlides/openslides-client pull request #1688
Opened 2022-10-13 08:22 UTC by luisa-beerboom

Closes #1685

2022-10-13 08:30 UTC, bastianjoel approved these changes

2022-10-19 16:58 UTC, emanuelschuetze requested changes
We need a better order of columns. I've a suggestion. Please ask me.

2022-10-27 10:05 UTC, emanuelschuetze requested changes
As discussed

2022-10-27 15:05 UTC, emanuelschuetze approved these changes

2022-10-27 15:06 UTC, merged