use radio buttons for motion analog vote majority selection
OpenSlides/openslides-client pull request #1695
Opened 2022-10-13 10:50 UTC by bastianjoel

resolves #1469 for motion votes.

2022-10-13 12:35 UTC, luisa-beerboom approved these changes

2022-10-13 14:22 UTC, emanuelschuetze requested changes
cannot deselect a selected radio button. I think a (disabled) checkbox is a better component instead radio button which cannot deselect.

2022-10-19 13:06 UTC, luisa-beerboom approved these changes

2022-10-19 16:44 UTC, emanuelschuetze approved these changes
works now as expected

2022-10-19 16:45 UTC, merged