Grey out motion detail nav buttons
OpenSlides/openslides-client pull request #1699
Opened 2022-10-14 11:03 UTC by luisa-beerboom

Closes #1698

2022-10-17 13:27 UTC, luisa-beerboom commented
Extracted the amendment navigation bug to issue #1704

2022-10-18 07:27 UTC, bastianjoel approved these changes

2022-10-19 15:41 UTC, emanuelschuetze requested changes
min-width would be helpful

2022-10-25 12:51 UTC, MSoeb approved these changes

2022-10-27 10:40 UTC, emanuelschuetze approved these changes

2022-10-27 10:40 UTC, merged