Solved a few problems with the account search selector
OpenSlides/openslides-client pull request #1700
Opened 2022-10-14 12:08 UTC by luisa-beerboom

Closes #1502

2022-10-18 07:49 UTC, bastianjoel approved these changes

2022-10-19 12:47 UTC, emanuelschuetze requested changes
Now, as committee admin, I cannot find/add any account in meeting admin search field...

2022-10-19 15:51 UTC, luisa-beerboom commented
> Now, as committee admin, I cannot find/add any account in meeting admin search field...

@emanuelschuetze This is unsurprising, since pure committee admins lack the rights required by the presenter, which is why I disabled the search function for them. This would therefore require backend changes

2022-10-27 10:43 UTC, emanuelschuetze approved these changes

2022-10-27 10:43 UTC, merged