Started implementing backend motion forwarding changes in client
OpenSlides/openslides-client pull request #1702
Opened 2022-10-17 08:19 UTC by luisa-beerboom

Closes #1675

2022-10-17 08:43 UTC, jsangmeister requested changes

2022-10-17 08:43 UTC, jsangmeister commented on client/src/app/infrastructure/definitions/relations/relations.ts
> +    // }),
remove

2022-10-17 08:43 UTC, jsangmeister commented on client/src/app/domain/models/motions/motion.ts
> +    public origin_meeting_id!: Id;
```suggestion
    public origin_meeting_id: Id;
```

2022-10-17 09:09 UTC, jsangmeister approved these changes
not tested

2022-10-18 07:30 UTC, emanuelschuetze approved these changes

2022-10-18 07:30 UTC, merged