recheck current route guards on permission change
OpenSlides/openslides-client pull request #1720
Opened 2022-10-20 12:52 UTC by bastianjoel

resolves #1439

2022-10-20 13:45 UTC, luisa-beerboom approved these changes

2022-10-20 13:50 UTC, luisa-beerboom approved these changes

2022-10-26 10:21 UTC, luisa-beerboom requested changes

2022-10-26 10:21 UTC, luisa-beerboom commented on client/src/app/site/guards/permission.guard.ts
> +                const meetingId = this.operator.onlyMeeting.toString();
Why not continue using forwardToOnlyMeeting here?
Haven't you changed it to do exactly what you are also doing here?

2022-10-26 10:21 UTC, luisa-beerboom commented on client/src/app/site/services/reroute.service.ts
> +    public forwardToOnlyMeeting(segments: string[] = []): UrlTree | void {
With your changes to take out the navigation most of the `RerouteService`'s method names don't fit anymore, please change names like `forwardToOnlyMeeting` that insinuate that they also handle the navigation to something more fitting like maybe `getOnlyMeetingUrlTree` (please don't forget to change the documentation either)

2022-10-26 11:35 UTC, luisa-beerboom approved these changes

2022-10-27 11:18 UTC, emanuelschuetze requested changes
Go as normal user to e.g. agenda list.
Now remove agenda.can_see permission.
-> User gets Authorization Error for agenda_item.can_see (OK)
Now click on "Back to OpenSlides" button which shows again a 2nd Authorization Error (for meeting.can_see_frontpage).
User has to click 2-3 times on "Back to OpenSlides" to go back to frontpage.

2022-10-28 11:53 UTC, bastianjoel commented
I can't replicate this. Anyway I've changed the way the error page redirects and hope this fixes the issue.

2022-11-04 08:46 UTC, emanuelschuetze requested changes
same problem, reproduceable for me

2022-11-09 10:20 UTC, bastianjoel commented
I can reproduce this now. Happens only in chromium.

2022-11-09 12:52 UTC, luisa-beerboom approved these changes

2022-11-09 13:00 UTC, luisa-beerboom approved these changes

2022-11-09 21:01 UTC, emanuelschuetze requested changes
Retested: Same error.
Get "Error: Uncaught (in promise): [object Undefined]" after clicking 2-3 times on "Back to OpenSlides"
Tested with Chromium and Firefox.

2022-11-10 11:53 UTC, emanuelschuetze approved these changes
Looks good now!

2022-11-10 11:54 UTC, merged