fix mediafile scrolling table after hide
OpenSlides/openslides-client pull request #1781
Opened 2022-11-08 12:49 UTC by bastianjoel

resolves #1768 

Currently when deleting all files from from file upload list the scrolling table gets destroyed. This also deletes the previously defined columns. With this pr the scrolling table only gets hidden.

2022-11-08 13:04 UTC, luisa-beerboom approved these changes

2022-11-09 06:43 UTC, emanuelschuetze requested changes
* works: select another file
* does not work: select the same file again for upload -> upload details not visible anymore

2022-11-09 10:07 UTC, luisa-beerboom approved these changes

2022-11-09 10:23 UTC, emanuelschuetze approved these changes

2022-11-09 10:23 UTC, merged