display organization description on calendar
OpenSlides/openslides-client pull request #1793
Opened 2022-11-11 15:41 UTC by bastianjoel

resolves #1778

2022-11-11 15:55 UTC, luisa-beerboom approved these changes

2022-11-14 07:50 UTC, emanuelschuetze requested changes
Error: `Property 'organizationDescription' does not exist on type 'DashboardComponent'`

And please show only description field - without mat-card.

2022-11-15 09:06 UTC, luisa-beerboom approved these changes

2022-11-15 16:31 UTC, emanuelschuetze approved these changes
I pushed some fixes for padding left/top on small devices. - Looks good now.

2022-11-15 16:46 UTC, merged