Fix pdf export Header text.
OpenSlides/openslides-client pull request #1840
Opened 2022-11-30 12:58 UTC by m-schieder

Fix #1830

2022-11-30 15:39 UTC, emanuelschuetze requested changes
Error if you try to export a single pdf (via motion detail view):
```
ERROR TypeError: Cannot read properties of undefined (reading 'pdfOptions')
    at PdfDocumentService.getHeader (pdf-document.service.ts:499:35)
```

2022-11-30 15:40 UTC, emanuelschuetze commented
Same for agenda, assignment, user list pdf

2022-11-30 16:41 UTC, emanuelschuetze approved these changes

2022-12-01 13:23 UTC, rrenkert approved these changes

2022-12-01 13:23 UTC, merged