improve client offline handling
OpenSlides/openslides-client pull request #1876
Opened 2022-12-16 13:01 UTC by bastianjoel

resolves #759 

Displays an error when client tries to send a request while offline.

2022-12-16 13:15 UTC, luisa-beerboom approved these changes

2022-12-16 13:16 UTC, luisa-beerboom commented
Code looks good, prettify fails though

2023-01-12 17:24 UTC, emanuelschuetze requested changes
New offline message is shown by trying to save edit form of  front page, topics, elections, user. But message is not show for project action, motion edit, motion meta data etc.

2023-01-18 13:29 UTC, luisa-beerboom approved these changes

2023-01-18 16:49 UTC, emanuelschuetze approved these changes

2023-01-18 16:50 UTC, merged