Built projection hint into detail views
OpenSlides/openslides-client pull request #1895
Opened 2023-01-10 10:30 UTC by luisa-beerboom

Closes #574 

Created own title component for meeting-side detail views that shows a camera icon when the model is projected.
Built it into topic, motion, assignment and list of speakers detail views, as well as into the motion-block-detail headbar.

For now I believe that the hint only shows for models that are projected on the standard projector, is this fine or should there also be a notification for the other projectors @emanuelschuetze ?

2023-01-10 11:11 UTC, bastianjoel approved these changes

2023-01-10 20:00 UTC, emanuelschuetze requested changes
Autoupdate does not work:
- in tab 1: open e.g. a motion detail view (motion is not projected)
- in tab 2: go to motion list and project the motion
=> tab 1 shows no projector hint icon, needs reload

2023-01-12 16:23 UTC, emanuelschuetze approved these changes

2023-01-18 09:23 UTC, bastianjoel approved these changes

2023-01-18 13:31 UTC, merged