[WIP] Projector button cleanup
OpenSlides/openslides-client pull request #1902
Opened 2023-01-11 13:24 UTC by luisa-beerboom

Closes #607 

TODO: 

- [ ] Unify ProjectorDetailComponent's projector buttons

2023-01-12 15:11 UTC, luisa-beerboom commented
Found and fixed a bug concerning current list of speakers projection (which would throw a bunch of errors) otherwise the projector buttons (changes especially happened for the ones in the projector detail view and the menu of the LoS detail view) should all function as they did before

2023-01-12 15:19 UTC, bastianjoel approved these changes

2023-01-18 09:31 UTC, bastianjoel requested changes
You could use `nonStableCurrentProjections` here and in the following occurrences of filtering non stable projections.

2023-01-18 09:35 UTC, bastianjoel requested changes

2023-01-18 09:35 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
> +        return !!this.projector.current_projections.filter(projection => projection.stable === false).length;
You could use `this.projector.nonStableCurrentProjections` here and in the following occurrences of filtering non stable projections.

2023-01-20 11:14 UTC, bastianjoel requested changes

2023-01-20 11:14 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
> +        for (let projection of this.projector.current_projections.filter(projection => projection.stable === false)) {
```suggestion
        for (let projection of this.projector.nonStableCurrentProjections) {
```

2023-01-20 11:14 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts
> +            )) {
```suggestion
            for (let projection of this.projector.nonStableCurrentProjections) {
```

2023-01-20 20:41 UTC, bastianjoel approved these changes

2023-01-27 07:12 UTC, emanuelschuetze approved these changes

2023-01-27 07:13 UTC, merged