fix meeting list getting cleared
OpenSlides/openslides-client pull request #1908
Opened 2023-01-12 15:13 UTC by bastianjoel

resolves #1892

Some relations currently have a isFullList property which indicates if a view model contains a complete list. When the property is set it seems to influence the behavior if a element is deleted on autoupdate.   

The problem is that it depends if a model is a full list on whether the user is inside a meeting or not. For the meeting list this is causing the elements to be deleted because their groups (which are marked as full list) are requested. 

This PR tries to fix that by giving the model request builder context on which model is the current root model.

2023-01-12 15:23 UTC, jsangmeister requested changes
I don't think that this is the best way to solve this, but if it works it's fine since I don't understand the `isFullList` either :D

2023-01-12 15:23 UTC, jsangmeister commented on client/src/app/site/services/model-request-builder/model-request-builder.service.ts
> +        if (relation.isFullList && relation.ownViewModels[0].name === this.rootViewModel) {
Can you use `COLLECTION` instead of `name`? That seems a little less hacky.

2023-01-12 15:34 UTC, jsangmeister approved these changes

2023-01-12 15:38 UTC, luisa-beerboom approved these changes
I don't really get the isFullList attribute either, but based on your explanation I think that, aside from one minor style thing, this looks good

2023-01-12 15:38 UTC, luisa-beerboom commented on client/src/app/site/services/model-request-builder/model-request-builder.service.ts
> +    public setRootViewModel(rootCollection: string) {
```suggestion
    public setRootViewModel(rootCollection: string): void {
```

2023-01-17 09:23 UTC, luisa-beerboom commented
@emanuelschuetze can you take a look if this also fixes issue #1892 ?
That one looks a bit like it may have the same cause.

2023-01-18 09:49 UTC, bastianjoel commented
> I don't think that this is the best way to solve this

It might be better to be able to specify and overwrite the isFullList property within the model request. What do you think about that @jsangmeister?

2023-01-18 17:59 UTC, emanuelschuetze commented
> @emanuelschuetze can you take a look if this also fixes issue #1929 ? That one looks a bit like it may have the same cause.

#1929 is not fixed with this PR: After deleting a meeting, the calender still shows the deleted meeting -> reload required.

2023-01-18 18:02 UTC, emanuelschuetze requested changes
#1892 is fixed now, but similar issue #1929 is not fixed. Can you fix it in this PR?

2023-01-19 09:00 UTC, luisa-beerboom commented
I would propose to do #1929 separately if that is the case, let's merge this first

2023-01-19 09:06 UTC, jsangmeister commented
> > I don't think that this is the best way to solve this
> 
> It might be better to be able to specify and overwrite the isFullList property within the model request. What do you think about that @jsangmeister?

Sounds better! If it's not too much work, I would favor this approach.

2023-01-20 11:41 UTC, bastianjoel commented
@emanuelschuetze I think #1929 should be done within another PR too.

2023-01-20 13:12 UTC, luisa-beerboom approved these changes

2023-01-20 14:22 UTC, emanuelschuetze approved these changes

2023-01-20 14:30 UTC, merged