[WIP] Export poll results as pdf
OpenSlides/openslides-client pull request #1933
Opened 2023-01-18 13:12 UTC by luisa-beerboom

TODO:

- [ ] Get rid of circular dependency
- [ ] Connect pdf-export-functionality to buttons in the detail view menu
- [ ] Get pdf generation to work
- [ ] Fix up exported pdf
- [ ] cleanup

2023-01-27 07:41 UTC, emanuelschuetze requested changes
Some minor (wording) issues:
1. Use "Single votes" instead of "Vote results" as title for first table.
2. Number als lines of both tables (to count single votes and entitled votes)
3. As file name use "$MotionIdentifiier-$PollName" (e.g. "A001-Abstimmung.pdf"). Please add motion identifier also in poll detail view head bar (currently there is just "Motion $PollName").
4. Add final vote result (summary) above both tables. Then this export has more value to archive (without count manually all votes).

2023-01-27 09:44 UTC, luisa-beerboom commented
> Some minor (wording) issues:
> 
>     1. Use "Single votes" instead of "Vote results" as title for first table.
> 
>     2. Number als lines of both tables (to count single votes and entitled votes)

I'm not sure what you mean, am I supposed to number the lines in the two tables?

> 
>     3. As file name use "$MotionIdentifiier-$PollName" (e.g. "A001-Abstimmung.pdf"). Please add motion identifier also in poll detail view head bar (currently there is just "Motion $PollName").

Alright, I can do that, what is the naming convention for assignment polls supposed to be?

> 
>     4. Add final vote result (summary) above both tables. Then this export has more value to archive (without count manually all votes).

2023-01-27 09:48 UTC, emanuelschuetze commented
> Alright, I can do that, what is the naming convention for assignment polls supposed to be?

"$ElectionTitel-$BallotName.pdf"

2023-01-27 20:41 UTC, emanuelschuetze requested changes
Please use the same column with for result table as for table 2 (single votes) and 3 (entitled users). Rest looks good!

2023-01-30 09:52 UTC, luisa-beerboom commented
I can't really get it to align perfectly, but I did manage to make it a little bit better

2023-01-31 08:52 UTC, bastianjoel commented on client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
> +        for (const date of resultsTable) {
It might be better to just iterate over the index numbers here.

2023-01-31 08:58 UTC, bastianjoel approved these changes

2023-01-31 08:58 UTC, bastianjoel commented on client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
> +        for (const date of resultsTable) {
It might be better to just iterate over the index numbers here.

2023-01-31 08:58 UTC, bastianjoel commented on client/src/app/site/pages/meetings/modules/poll/base/base-poll-pdf.service.ts
> +        )) {
It could be iterated over index numbers here too.

2023-01-31 20:22 UTC, emanuelschuetze approved these changes

2023-01-31 20:23 UTC, merged