Implemented account list active meeting filter + Orga statistics rework
OpenSlides/openslides-client pull request #1956
Opened 2023-01-24 12:34 UTC by luisa-beerboom

Closes #1953

2023-01-24 12:44 UTC, bastianjoel approved these changes

2023-01-27 08:02 UTC, emanuelschuetze requested changes
A user who is in two meeting (active + archived) was not filtered correctly if filter for archived meeting is seleted -> use is not displayed! (works for filter for active meeting)

2023-01-27 08:25 UTC, luisa-beerboom commented
> A user who is in two meeting (active + archived) was not filtered correctly if filter for archived meeting is seleted -> use is not displayed! (works for filter for active meeting)

That is unsurprising since the filter only differentiates between users which have active meetings and those that don't have any active meetings at all.

There is currently no "is in archived meetings" filter.
Since this seems to be a functional requirement I will build one in, it will be a separate filter though.

2023-01-27 10:08 UTC, bastianjoel approved these changes

2023-01-27 20:34 UTC, emanuelschuetze approved these changes
good performance (tested with 10k accounts)

2023-01-27 20:35 UTC, merged