Repaired getUploadFileJson function error catching
OpenSlides/openslides-client pull request #1964
Opened 2023-01-25 11:17 UTC by luisa-beerboom

Closes #1962 

Meeting and workflow imports should now throw a sensible error message if the json is not formatted correctly.

To test:
1. Take a json file that should  work
2. Break it (f.e. by adding a `,` after the last element of any array that is included in it)
3. When using it in the user import, pressing the upload button should throw an error "Import data needs to have the JSON format" along with showing with an equivalent snackbar message

2023-01-25 12:57 UTC, jsangmeister requested changes

2023-01-27 09:23 UTC, jsangmeister requested changes
Looks much better!

2023-01-27 09:23 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-import/workflow-import.component.ts
> +        private translate: TranslateService,
You can remove these dependencies here

2023-01-27 10:19 UTC, bastianjoel requested changes

2023-01-27 10:19 UTC, bastianjoel commented on client/src/app/infrastructure/utils/import/json-import-file-utils.ts
> +export async function getUploadFileJson<ExpectType>(
It seems to me like this function can be completely removed. I couldn't find any more references to it.

2023-02-06 07:37 UTC, jsangmeister approved these changes

2023-02-06 20:27 UTC, emanuelschuetze approved these changes

2023-02-06 20:38 UTC, merged