Slight iconage rework
OpenSlides/openslides-client pull request #1966
Opened 2023-01-25 14:02 UTC by luisa-beerboom

Closes #1965 

Aside from icon changes described in issue I also did the following (discussed with Martin):

- Orga-tag dialog's random colour generation button now uses mat-icon `autorenew`
- Participant-list > multiselect > set natural person button now uses mat-icon `sync`
- Motion-list > Statute button now uses mat-icon `gavel`

2023-01-25 15:34 UTC, rrenkert commented
@MSoeb will give feedback.

2023-01-27 08:13 UTC, emanuelschuetze requested changes

2023-01-27 08:13 UTC, emanuelschuetze commented on client/src/app/site/pages/organization/modules/navigation/organization-navigation/organization-navigation.component.ts
> +            icon: `auto_awesome_mosaic`,
As discussed: Please use "apps" icon (as in meeting back button) instead of old committee icon "auto_awesome_mosaic".

2023-01-27 10:50 UTC, emanuelschuetze submitted a review, later dismissed

2023-02-12 16:41 UTC, emanuelschuetze approved these changes
New committee icon (in main menu and calendar items) and calendar icon (in main menu) looks good for me.
@MSoeb Please have a look and give a short feedback.
Here a screenshot:
![new-icons](https://user-images.githubusercontent.com/2075427/218324481-85c0d76e-6da0-4cf3-8a91-b757b5d7a55b.png)


One note: An account which is assigned to a meeting shows still (old) calendar icon in list. Ok for me, because the "apps" icon (from new calendar) does not match in this case.
![account-list](https://user-images.githubusercontent.com/2075427/218324526-655b787f-edbb-4f91-9562-6a876e0dd0ca.png)

2023-02-13 08:07 UTC, luisa-beerboom commented
> One note: An account which is assigned to a meeting shows still (old) calendar icon in list. Ok for me, because the "apps" icon (from new calendar) does not match in this case.

See PR #1974 There the old meeting logo is used for the new meeting-list.

2023-02-13 10:49 UTC, MSoeb commented
@emanuelschuetze I'm a bit confused. I thought that the committee icon should be with people at a table. The new one looks like the logo of Only Office. Except from this, the icon is okay. But at the first glance I would not associate it with a committee.

Calendar Icon: Same here, I would not associate it with a calender. It looks more like the Drag&Drop Icon in a meeting.

Overall the icons are okay, but I would not prefer them.

2023-02-23 10:33 UTC, emanuelschuetze commented
@luisa-beerboom as discussed

2023-02-24 10:09 UTC, luisa-beerboom commented
Has been unified with #1974 and will be continued there

2023-02-24 10:09 UTC, closed without merging