Implemented isUniqueAmong validator for motion numbers and category…
OpenSlides/openslides-client pull request #1993
Opened 2023-02-01 12:58 UTC by luisa-beerboom

…prefixes

Closes #1986

2023-02-03 08:26 UTC, bastianjoel approved these changes

2023-02-06 19:45 UTC, emanuelschuetze requested changes
Does not work for multi select action of set state:
* set in motion settings the default workflow to complex workflow
* create 3 new motions => all motions have empty number
* select all 3 motions > multiselect > set state > select "permitted"
=> all 3 motions get same number (e.g. "01")
expected: sequential, unique number (e.g. 01, 02, 03)

2023-02-07 13:50 UTC, jsangmeister commented
This is a backend issue. I will fix this

2023-02-15 19:54 UTC, emanuelschuetze approved these changes
tested successfully - also tested with OpenSlides/openslides-backend/pull/1624

2023-02-15 19:54 UTC, merged