Adds pro/contra-speech feature to los
OpenSlides/openslides-client pull request #202
Opened 2021-04-28 14:15 UTC by GabrielInTheWorld

As [OS3](https://github.com/OpenSlides/OpenSlides/pull/6023)

2021-04-29 05:53 UTC, FinnStutzenstein commented
Hi, please have a look at https://github.com/OpenSlides/OpenSlides/pull/6038 (and the linked issue)

2021-04-29 06:25 UTC, FinnStutzenstein approved these changes

2021-04-29 06:25 UTC, FinnStutzenstein commented on client/src/app/core/repositories/event-management/meeting-settings-definition.ts
> +                    },
The order was changed in the final PR (also check the wording)

2021-04-29 06:25 UTC, FinnStutzenstein commented on client/src/app/core/repositories/agenda/speaker-repository.service.ts
> +    public setProContraSpeech(speaker: ViewSpeaker, isProSpeech: boolean): Promise<void> {
See my comment: this has changed a bit.

2021-04-29 06:25 UTC, FinnStutzenstein commented on client/src/app/shared/components/list-of-speakers-content/list-of-speakers-content.component.ts
> +    public get showSpeakersOrderNote(): boolean {
See comment about the new fix-PR

2021-05-04 10:33 UTC, tsiegleauq approved these changes
Looks good. Works without issues on the client. Server seems not ready yet, so cannot be merged from my side

2021-05-05 16:00 UTC, tsiegleauq requested changes

2021-05-05 16:00 UTC, tsiegleauq commented on client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.html
> +                                <ng-container *ngIf="hasPerms('manage')">
This was a bug in the original code. Move "hasPerms" to the `remove-candidate` button

2021-06-03 06:50 UTC, FinnStutzenstein commented
Please have a look into https://github.com/OpenSlides/OpenSlides/wiki/speaker.update and the models.yml

There is now just one field `speech_state` which is a combination of `pro_speech` and `marked` in OS3.

2021-06-03 10:21 UTC, FinnStutzenstein commented
You may build upon https://github.com/OpenSlides/openslides-backend/pull/740

2021-06-09 13:18 UTC, tsiegleauq commented
could directly integrate the following changes:
https://github.com/OpenSlides/OpenSlides/pull/6073/files

2021-06-10 14:51 UTC, GabrielInTheWorld commented
@tsiegleauq I have reworked this. You can review it again.

2021-06-11 13:27 UTC, tsiegleauq approved these changes
perfect. Rebase and merge

2021-06-11 13:39 UTC, tsiegleauq commented
hm I think I broke something.

2021-06-11 13:43 UTC, tsiegleauq commented
ok that should do it.

2021-06-11 13:53 UTC, merged