agenda item poll PDF export
OpenSlides/openslides-client pull request #2038
Opened 2023-02-17 15:18 UTC by bastianjoel

resolves #2030 

Adds an export for poll results and ballot papers to agenda polls.

2023-02-23 09:34 UTC, luisa-beerboom requested changes

2023-02-23 09:34 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/services/topic-pdf.service/topic-pdf.service.ts
> +                        text: this.translate.instant(`Candidates`),
`Candidates` in a topic poll? Topic polls have text options so it should just be `Options`

2023-02-27 08:27 UTC, luisa-beerboom approved these changes

2023-02-27 19:16 UTC, emanuelschuetze commented
Works good as single pdf which can be generated from topic detail view.
It would be great to export multiple topic items in one pdf (via multiaction) OR/AND via an agenda export dialog for all agenda items (this could be a bit more work).

2023-02-28 11:33 UTC, bastianjoel commented
> Works good as single pdf which can be generated from topic detail view. It would be great to export multiple topic items in one pdf (via multiaction) OR/AND via an agenda export dialog for all agenda items (this could be a bit more work).

There is already another issue for that #2032

2023-03-01 19:43 UTC, emanuelschuetze approved these changes

2023-03-01 19:45 UTC, merged