Fixes creation of amendments
OpenSlides/openslides-client pull request #205
Opened 2021-04-29 11:51 UTC by GabrielInTheWorld

Fixes #195 
Fixes [openslides-backend#696](https://github.com/OpenSlides/openslides-backend/issues/696)

Waiting for #187

2021-04-29 12:05 UTC, tsiegleauq commented
> Waiting for #187

Why? This seems unrelated.

2021-04-29 12:21 UTC, FinnStutzenstein approved these changes
Looks good, not tested

2021-04-29 12:27 UTC, GabrielInTheWorld commented
> > Waiting for #187
> 
> Why? This seems unrelated.

I meant #190: [active-meeting-id.service.ts#L35](https://github.com/OpenSlides/openslides-client/blob/0a018e1c60252540d4e62abc5c05a5449c76f54c/client/src/app/core/core-services/active-meeting-id.service.ts#L35) has an error, which prevents the creation of an amendment. #190 has a fix for that.

2021-05-03 14:19 UTC, tsiegleauq requested changes
Paragraph based amendments are almost fine.
Text changes are not saved or rendered in the motion.
In Settings, set "how to create new amendments" to "Paragraph-based, Diff-enabled".

Create a new Amendment of motion/1
Select a paragraph and change

The parent was set just fine,
It appears as an amendment to motion/1,
The text changes show : "No changes at the text." (in italic)

using **"Empty text field"**:
"new-amendment?parent=1" was set just fine.
Saving the new amendment was submitting a new motion that was not regisered to be an amendment. The detail view does not show the parent, the supposed-to-be parent does not show the amendment

using: **"Edit the whole motion text"**
Same as above, but the motion text of the parent was missing in tinyMCE

2021-05-31 10:35 UTC, tsiegleauq requested changes
There is still something really odd with paragraph based amendments.

* updating (changing) a paragraph based amendment does not work. The save button is always disabled
* in the view of a paragraph based amendment: switching between line number modes **duplicates the text**. That one is really odd.

before:
![image](https://user-images.githubusercontent.com/10233032/120180744-6f70ed80-c20c-11eb-8f29-9decf983ebce.png)

changing line number outside once:
![image](https://user-images.githubusercontent.com/10233032/120180892-9deec880-c20c-11eb-9da0-7098c0058e4e.png)

changing back to no line numbers:
![image](https://user-images.githubusercontent.com/10233032/120180938-acd57b00-c20c-11eb-8267-028d6dba4b1c.png)

changing to outside again:
![image](https://user-images.githubusercontent.com/10233032/120180973-b8c13d00-c20c-11eb-9584-a101aba3a08a.png)

2021-06-07 16:21 UTC, GabrielInTheWorld commented
@tsiegleauq Please re-test and let me know, if everything is okay or anything is missing.

2021-06-09 10:50 UTC, tsiegleauq approved these changes
Works as expected. There were other unrelated (non breaking) bugs that we might take care of later. Not entirely sure if the structure is optimal yet, especially regarding `base-motion-detail-child.component.ts `, but we might tackle this another time. Can be rebased and merged.

2021-06-09 10:50 UTC, tsiegleauq commented on client/src/app/site/motions/modules/motion-detail/components/base/base-motion-detail-child.component.ts
> +export class BaseMotionDetailChildComponent extends BaseComponent {
base class directive should probably be abstract if you never plan to actually make it an instance or a component

2021-06-10 06:49 UTC, merged