Realigned meeting settings titles vertically
OpenSlides/openslides-client pull request #2095
Opened 2023-03-15 12:15 UTC by luisa-beerboom

closes #2067

2023-03-15 12:24 UTC, bastianjoel requested changes

2023-03-15 12:24 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-list/components/meeting-settings-group-list/meeting-settings-group-list.component.scss
> +    }
```suggestion
    .flex-center,
    .flex-center-unsafe {
        height: 50%;
    }
```

2023-03-15 13:25 UTC, bastianjoel approved these changes

2023-03-16 11:39 UTC, emanuelschuetze approved these changes

2023-03-16 11:41 UTC, merged