moved and added dialog for "is active" button
OpenSlides/openslides-client pull request #2163
Opened 2023-04-03 09:33 UTC by Elblinator

resolves #2120

2023-04-04 13:54 UTC, emanuelschuetze commented on client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.ts
> +        const content = `This will change the design in all committees.`;
Just a spelling issue: Please use "meetings" instead of "committees" (because users working with/in meetings not in committee detail views).

2023-04-04 13:54 UTC, emanuelschuetze approved these changes
One remark. Rest looks good.

2023-04-04 13:55 UTC, emanuelschuetze commented
Please add to https://github.com/OpenSlides/OpenSlides/blob/main/AUTHORS with reference to this (your first) PR.

2023-04-12 13:41 UTC, bastianjoel requested changes
Looks good overall. Just some minor remarks.

2023-04-12 13:41 UTC, bastianjoel commented on client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.ts
> +        );
I think it might be a good idea to make these values also settable by an attribute to make this more reusable.

2023-04-12 13:41 UTC, bastianjoel commented on client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.ts
> +    @Output() selected = new EventEmitter<boolean>();
Add `public` keyword infront of `selected`

2023-04-12 13:41 UTC, bastianjoel commented on client/src/app/ui/modules/prompt-checkbox/components/prompt-checkbox/prompt-checkbox.component.ts
> +    @Output() selected = new EventEmitter<boolean>();
It is good practice to add a short description to public members especially for components that should be reusable. 

```suggestion
    /**
      * Indicates if the checkbox is checked
      */
    @Input() 
    public checked: boolean;
    
    /**
      * ...
      */
    @Input() 
    public disabled: boolean;
    
    /**
      * ...
      */
    @Output() 
    selected = new EventEmitter<boolean>();
```

2023-04-12 13:41 UTC, bastianjoel commented on client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
There is something wrong with the formatting of this file.

2023-04-14 07:14 UTC, bastianjoel requested changes

2023-04-14 07:14 UTC, bastianjoel commented on client/src/app/site/pages/organization/pages/designs/pages/theme-list/components/theme-list/theme-list.component.html
> +        *osScrollingTableCell="'colors'; row as theme; config: { width: 120 }"
Please remove trailing spaces

2023-04-14 08:43 UTC, bastianjoel approved these changes

2023-04-20 07:46 UTC, emanuelschuetze approved these changes

2023-04-20 07:47 UTC, merged