Added functionality for clear motion block choice
OpenSlides/openslides-client pull request #2187
Opened 2023-04-11 14:14 UTC by luisa-beerboom

Closes #2153

2023-04-12 12:36 UTC, bastianjoel approved these changes

2023-04-13 09:46 UTC, rrenkert requested changes
Maybe an edge case, but:
* Clear the motion block as described in the issue
* Keep the motion block dialog open
* Try to set a motion block
-> dialog closes without setting the block.

The data object of motion.update does not contain the block_id.

2023-04-13 12:09 UTC, luisa-beerboom commented
>     * Keep the motion block dialog open

???
If a Motion block is cleared through the dialog, the dialog will close?
What exactly are you doing @rrenkert ?

2023-04-14 14:37 UTC, rrenkert approved these changes

2023-04-14 14:37 UTC, merged