fix livestream sometimes not displayed
OpenSlides/openslides-client pull request #2192
Opened 2023-04-12 12:22 UTC by bastianjoel

resolves #2189

2023-04-12 12:49 UTC, luisa-beerboom approved these changes

2023-04-14 11:34 UTC, luisa-beerboom requested changes
Generally looks good to me, just one question

2023-04-14 11:34 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/services/active-meeting.subscription.ts
> +                                            fieldset: [...MEETING_ROUTING_FIELDS],
Do you really need to request the sequential number and meeting id for all of these? If not, couldn't you just leave them out and not request any fields for the connective models at all?

2023-04-18 09:33 UTC, bastianjoel commented
Mind that it is possible that this still sometimes does not work because of https://github.com/OpenSlides/openslides-autoupdate-service/issues/666

2023-04-21 15:49 UTC, m-schieder approved these changes

2023-04-21 15:50 UTC, merged