Made motion detail recognize if the text is loaded
OpenSlides/openslides-client pull request #2202
Opened 2023-04-14 13:42 UTC by luisa-beerboom

Closes #2198

2023-04-14 14:24 UTC, emanuelschuetze approved these changes

2023-04-14 16:02 UTC, bastianjoel requested changes

2023-04-14 16:02 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
> +            });
The subscription could be closed after the first value was received.

2023-04-17 08:11 UTC, bastianjoel approved these changes

2023-04-20 07:42 UTC, emanuelschuetze approved these changes

2023-04-20 07:42 UTC, merged