set autopilot min height
OpenSlides/openslides-client pull request #2237
Opened 2023-04-25 11:51 UTC by bastianjoel

This is to prevent the scoll bar from flickering by just always displaying it.

resolves #2024

2023-04-25 12:06 UTC, jsangmeister commented
Can you wrap this in media queries so it only triggers on the specific pixels where it is required to? Always displaying the scroll bar could also be archieved with `overflow-y: scroll`, right?

2023-05-08 14:25 UTC, bastianjoel commented
This now also resolves ##2259 partially. Head bars will not scroll away anymore as they are added to the global headbar instead of the page content.

2023-05-09 13:35 UTC, luisa-beerboom requested changes
Just one styling remark

2023-05-09 13:35 UTC, luisa-beerboom commented on client/src/app/site/modules/global-headbar/global-headbar.service.ts
> +    public get headbar() {
Return type

2023-05-10 19:03 UTC, emanuelschuetze approved these changes

2023-05-11 08:01 UTC, luisa-beerboom approved these changes
@bastianjoel please fix the styling at a later date

2023-05-11 08:14 UTC, merged