Implement backend topic import
OpenSlides/openslides-client pull request #2244
Opened 2023-04-26 15:49 UTC by luisa-beerboom

2023-05-10 07:26 UTC, rrenkert requested changes
* In the fullscreen preview dialog the row content does not fit the table header:
![Tagesordnung - OpenSlides - rtf staging openslides com](https://github.com/OpenSlides/openslides-client/assets/19685715/3eafc926-edec-45a9-a881-4030d0c93e76)

* Closing this dialog clears the embedded table.
* The preview should disappear after successful import (offer a navigation to the agenda?)

2023-05-16 07:12 UTC, bastianjoel approved these changes

2023-05-30 11:33 UTC, rrenkert requested changes
* In full screen the columns "title", "text", and "comment" should use kind of dynamic width.
* After performing an initial import a dialog "Stopped waiting for process(es)" comes up. Refreshing the list view shows all imported items.
* After perfoming an import the user can select a new file to import, but no new preview is shown.

2023-05-30 11:33 UTC, rrenkert requested changes
* In full screen the columns "title", "text", and "comment" should use kind of dynamic width.
* After performing an initial import a dialog "Stopped waiting for process(es)" comes up. Refreshing the list view shows all imported items.
* After perfoming an import the user can select a new file to import, but no new preview is shown.

2023-05-30 15:56 UTC, bastianjoel approved these changes

2023-05-30 15:57 UTC, luisa-beerboom commented
> * In full screen the columns "title", "text", and "comment" should use kind of dynamic width.
> 
>     * After performing an initial import a dialog "Stopped waiting for process(es)" comes up. Refreshing the list view shows all imported items.
> 
>     * After perfoming an import the user can select a new file to import, but no new preview is shown.

I only fixed the first one, as I can't replicate the others. Are you sure that your instance is working correctly @rrenkert ?

2023-06-15 15:10 UTC, rrenkert commented
Looks good so far.

Some minor things:
* Importing duplicated topics shows a misleading tooltip "Duplizieren" for the warning icon.
* After a successful import the summary shows
  
Total topics:	 19
Topics with warnings (will be skipped):	 19

better would be

Total topics:	 19
Topics skipped:	 17
Topics created: 2

> I only fixed the first one, as I can't replicate the others. Are you sure that your instance is working correctly @rrenkert ?
I can still replicate the one with the second file upload:
* select a file and perform the import.
* select the same file again -> nothing happens.

2023-06-15 15:11 UTC, rrenkert requested changes
please see my last comment.

2023-08-11 13:11 UTC, rrenkert commented
Additional info for the second file upload: Happens in Chromium based browsers.

Another point: When selecting a file for upload a scrollbar appears in the upper card.

2023-08-11 14:29 UTC, bastianjoel requested changes

2023-08-11 14:29 UTC, bastianjoel commented on client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
> +    <div style="margin-bottom: 5px">
Not entirely sure but afaik our linter should complain about inline style definitions. Use a class instead if possible.

2023-08-11 14:39 UTC, rrenkert approved these changes
Works as expected now.

2023-08-11 14:40 UTC, bastianjoel approved these changes

2023-08-11 14:43 UTC, merged