fix missing autoupdate for amendment change recommendations
OpenSlides/openslides-client pull request #2256
Opened 2023-05-03 13:27 UTC by bastianjoel

resolves #2225

2023-05-03 15:11 UTC, rrenkert approved these changes

2023-05-04 17:39 UTC, emanuelschuetze requested changes
Change recommendations are NOT loaded ...
* ... if you reload the amendment list view -> wrong diff without change recommendation
* ... if you export PDF in motion list view -> wrong diff without change recommendation (tested with/without settings option to show amendments in motion list)

2023-05-05 06:56 UTC, bastianjoel commented
The problem within the PDF export does not seem to be related to a missing subscription. Therefore I would suggest opening another issue for that.

2023-05-05 08:59 UTC, emanuelschuetze commented
> The problem within the PDF export does not seem to be related to a missing subscription. Therefore I would suggest opening another issue for that.

New issue created: https://github.com/OpenSlides/openslides-client/issues/2257

2023-05-05 08:59 UTC, emanuelschuetze approved these changes

2023-05-05 09:00 UTC, merged