Made amendment free text show on projection
OpenSlides/openslides-client pull request #2258
Opened 2023-05-05 10:39 UTC by luisa-beerboom

Closes #2218

2023-05-05 12:16 UTC, emanuelschuetze requested changes
If you disable the motion settings "Show motion text on projector" the projected free text  amendment still shows "No changes on the text":

![amendment-free-projection](https://user-images.githubusercontent.com/2075427/236455182-693a7cfa-f854-4620-a5f4-109e595ae21d.png)

2023-05-05 15:08 UTC, luisa-beerboom commented
> If you disable the motion settings "Show motion text on projector" the projected free text amendment still shows "No changes on the text":
> 
> ![amendment-free-projection](https://user-images.githubusercontent.com/2075427/236455182-693a7cfa-f854-4620-a5f4-109e595ae21d.png)

That's an autoupdate problem

2023-05-08 13:48 UTC, bastianjoel requested changes

2023-05-08 13:48 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
> +        console.log(`BASETEXT`, baseText, this.getAllTextChangingObjects());
Debug output should be removed

2023-05-08 20:28 UTC, emanuelschuetze submitted a review, later dismissed
The projector shows still amendment text if settings "Show motion text on projector"  is disabled.

2023-05-09 07:26 UTC, luisa-beerboom commented
> The projector shows still amendment text if settings "Show motion text on projector" is disabled.

So what do you want the projector to show for text amendments if the setting is disabled?

2023-05-09 10:23 UTC, luisa-beerboom commented
Update: It should not show any text at all.
No "The assembly may decide" and no "No changes at the text", just title and submitters

2023-05-10 10:47 UTC, bastianjoel approved these changes

2023-05-10 15:53 UTC, luisa-beerboom commented
Update after talking to @emanuelschuetze 
Disabling motion texts on projector _should_ disable any and all text _including_ diff lines for paragraph based amendments. The entire block down from and including "The assembly may decide" should be gone regardless of motion type, as soon as the setting is disabled!

TODO:
- [ ] Change the component to never show that block when the setting is disabled.
- [ ] Make an autoupdate issue/PR that removes the amendment paragraph information as well if the setting is disabled (since it is unnecessary at that point)

2023-05-15 12:18 UTC, bastianjoel approved these changes

2023-05-15 12:32 UTC, luisa-beerboom commented
>     * [x]  Make an autoupdate issue/PR that removes the amendment paragraph information as well if the setting is disabled (since it is unnecessary at that point)

=> OpenSlides/openslides-autoupdate-service#687

2023-05-16 10:57 UTC, luisa-beerboom commented
Merged upon request

2023-05-16 11:04 UTC, merged