better email not sent error messages
OpenSlides/openslides-client pull request #2295
Opened 2023-05-15 14:04 UTC by bastianjoel

resolves #2261

2023-05-15 15:08 UTC, luisa-beerboom reviewed
What about the case when the backend sends "has no valid email address"? I think any error that may potentially be caused by the user that sees the message should probably be specified...

2023-05-15 15:19 UTC, jsangmeister commented
How about we introduce error codes for this in the backend? This string matching does not seem like the best option.

2023-05-16 16:42 UTC, emanuelschuetze requested changes
I get this TypeError if I try to send emails and change `EMAIL_CONNECTION_SECURITY` to `"SSL/TLS"` (with quotes) to reproduce an error:
```
 TypeError: Cannot read properties of null (reading 'message')
    at http.service.ts:87:35
```

2023-06-12 12:53 UTC, luisa-beerboom approved these changes

2023-06-26 14:18 UTC, emanuelschuetze approved these changes

2023-06-26 14:18 UTC, merged