client sso implementation
OpenSlides/openslides-client pull request #2296
Opened 2023-05-15 15:18 UTC by bastianjoel

resolves #2285

2023-05-15 15:36 UTC, luisa-beerboom requested changes

2023-05-15 15:36 UTC, luisa-beerboom commented on client/src/app/site/pages/organization/pages/settings/modules/settings-detail/components/organization-settings/organization-settings.component.html
> +                    <input matInput formControlName="save_attr_config" />
Make this multi-line please

2023-05-16 09:55 UTC, luisa-beerboom approved these changes

2023-06-08 08:27 UTC, emanuelschuetze commented
@bastianjoel Please rebase on top of current main for easier testing this branch. Thx.

2023-06-14 07:57 UTC, merged