Made motion title update
OpenSlides/openslides-client pull request #2301
Opened 2023-05-16 14:13 UTC by luisa-beerboom

Closes #2287

2023-05-16 14:35 UTC, bastianjoel requested changes
I don't like this solution. I would prefer doing this by adding a public member method to `ProjectableTitleComponent` which will be called from `MotionManageTitleComponent` by using `ViewChild`.

2023-05-16 15:17 UTC, bastianjoel approved these changes

2023-05-16 15:20 UTC, bastianjoel requested changes

2023-05-16 15:20 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-manage-title/motion-manage-title.component.ts
> +        });
This should be added to `this.subscriptions`.

2023-05-16 15:56 UTC, emanuelschuetze approved these changes

2023-05-17 10:25 UTC, bastianjoel approved these changes

2023-05-22 11:56 UTC, emanuelschuetze approved these changes

2023-05-22 11:56 UTC, merged