Made user scope requesting method filter for the operator
OpenSlides/openslides-client pull request #2318
Opened 2023-05-23 14:35 UTC by luisa-beerboom

Closes #2282

2023-05-23 15:05 UTC, bastianjoel requested changes

2023-05-23 15:05 UTC, bastianjoel commented on client/src/app/site/services/user.service.ts
> +        }
I don't think it is necessary to check for existence first. 
 
```suggestion
        userIds = userIds.filter(id => id !== this.operator.operatorId);
```

2023-05-24 09:56 UTC, bastianjoel approved these changes

2023-06-02 11:55 UTC, emanuelschuetze approved these changes

2023-06-02 11:55 UTC, merged