Implement create child item button on agenda
OpenSlides/openslides-client pull request #2337
Opened 2023-05-25 10:25 UTC by luisa-beerboom

Closes #2308

2023-05-30 11:32 UTC, bastianjoel requested changes

2023-05-30 11:32 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail-main/topic-detail-main.component.ts
> +    }
It might be better to just use `AGENDA_LIST_ITEM_MINIMAL_SUBSCRIPTION` instead.

2023-05-30 12:40 UTC, bastianjoel approved these changes

2023-05-31 13:33 UTC, Elblinator requested changes
The parent field is correctly selected when the child is created, meaning the wanted function is created 

But the preselected parent field is not visibly selected in the creating view. 

The preselected field needs to be visibly selected.

2023-05-31 14:04 UTC, Elblinator approved these changes

2023-05-31 14:05 UTC, merged