Make participant create wizard update user correctly
OpenSlides/openslides-client pull request #2338
Opened 2023-05-26 11:55 UTC by luisa-beerboom

Closes #2094

2023-05-30 12:57 UTC, bastianjoel requested changes

2023-05-31 08:04 UTC, luisa-beerboom commented on client/src/app/site/modules/user-components/components/user-detail-view/user-detail-view.component.ts
>              }
Without this code, when immediately referencing an account, the checkboxes for natural person and active/inactive will be disabled.

2023-06-02 12:36 UTC, Elblinator requested changes
if the existing user is selected in step 2, the new data of the selected user will be displayed. 

But after the correct data is displayed in step 3:

- click 'previous' to go to step 2
- click 'previous' to go to step 1
- change username to new user 
- select 'next' 
- the data from the previously selected account will be displayed

2023-06-12 12:56 UTC, bastianjoel approved these changes
This seems like a lot of workarounds. I am fine with merging this but I would prefer to just do a cleanup or maybe a rewrite of this component.

2023-06-14 12:37 UTC, Elblinator requested changes
Now step 3 will display the correct data.

But:

1. in step one create a new user A
2. step 3 correctly displays the data
3. back to step 1, change username to already existing user B
4. in step 2 select already existing user B
5. data will be correctly displayed in step 3
6. back to step 1, change all the data back into a non-existing user C
7. step 3 will display data correctly
8. press save
9. one of two thing can now happen: 
-  a) either a new user is created with the data from the in 4. selected user B
- b) The Errormessage: Error: _A user with the username "B" already exists._ is displayed

the data from the new user C should be saved inside a user profile

2023-06-16 08:31 UTC, Elblinator approved these changes

2023-06-20 09:38 UTC, bastianjoel approved these changes
Please create a cleanup issue for the participant create wizard.

2023-06-20 12:54 UTC, merged