do not search for id fields in list search service
OpenSlides/openslides-client pull request #2344
Opened 2023-05-30 11:19 UTC by bastianjoel

resolves #2343 

This now disables searching for ids in all list views.

2023-05-30 12:25 UTC, luisa-beerboom requested changes
Shouldn't you at least put it back in for orga-level models that are navigated to via id? (meeting, committee, account)?

2023-06-02 13:38 UTC, emanuelschuetze commented
> @emanuelschuetze Should the search field be able to search for every visible item in a motion? -> if we search for '17', should the results include motions with a tag '17', with the state '17', etc.

This is not required because tags and states are selectable in dropdown filter menu. This PR should search by strings/numbers which are not in filter list.

2023-06-02 13:38 UTC, emanuelschuetze approved these changes
works good

2023-06-05 10:20 UTC, luisa-beerboom approved these changes

2023-06-05 10:20 UTC, merged