Fix filter buttons
OpenSlides/openslides-client pull request #2358
Opened 2023-06-01 09:29 UTC by luisa-beerboom

Closes #2357

2023-06-02 12:03 UTC, Elblinator requested changes
After selecting filters the first click still doesn't deactivate the button. 
It doesn't matter whether the x or anywhere else on the button is clicked.

2023-06-07 13:38 UTC, bastianjoel reviewed
This does not seem right and I cannot replicate the issue on current main.

2023-06-14 10:55 UTC, Elblinator approved these changes

2023-07-10 08:06 UTC, Elblinator requested changes
X in participants is still not working immediately

2023-08-16 10:03 UTC, closed without merging