Make list of speakers rearrangeable on mobile
OpenSlides/openslides-client pull request #2375
Opened 2023-06-06 11:24 UTC by bastianjoel

proposal to resolve #2306 

This PR enables the rearrangement functionality for mobile devices. To deal with accidental rearrangements a delay was added. A user has to hold the rearrangement icon for a certain time before they can move it. This way when scrolling over the page the user will not accidentally move an entry. 

The Angular Material documentation mentions the used functionality to deal with these scenarios so I think this is the way to go here. https://material.angular.io/cdk/drag-drop/overview#delayed-dragging
Although we might need to adjust the delay time.

2023-06-06 14:33 UTC, Elblinator requested changes
There is no visual feedback that the user can move the item after they held the item long enough.

An easy solution would be to slightly change the colour of the movable tile

2023-07-12 10:02 UTC, bastianjoel commented
I will close this one for now as a visual feedback does not seem to be possible with angular materials API and we therefore might need a different solution.

2023-09-07 07:49 UTC, Eich-hoernchen commented
Tested it, the feedback looks good. 

I found another bug in the mobile view. On the small devices the More Vert icon falls of the tile.

![image](https://github.com/OpenSlides/openslides-client/assets/60174105/44a3a6bf-4804-4cd9-92f5-200c38a3317a)

2023-09-08 05:57 UTC, Elblinator approved these changes

2023-09-08 06:03 UTC, merged