Livestream window should not overlap other elements
OpenSlides/openslides-client pull request #2411
Opened 2023-06-13 14:04 UTC by luisa-beerboom

Closes #2367 

Also restyles some views that didn't use standard OpenSlides card styling (category-detail, category-list-sort), please have a look at category detail in particular when testing

2023-06-16 14:18 UTC, emanuelschuetze submitted a review, later dismissed
* Please add a border bottom line for the last table line
* Add more bottom space in settings view (e.g. motion settings)

2023-06-20 09:47 UTC, bastianjoel requested changes
I would prefer adding the spacing globally to a container element.

2023-06-21 10:00 UTC, luisa-beerboom commented
@emanuelschuetze 
1. I took out the bottom lines for the list views specifically because it would make the new spacer look like there is some artefact data that isn't being displayed properly
2. Why should the meeting settings get even more spacer? They already have the standard 60px spacer that is necessary to accommodate the livestream window?

2023-08-28 11:08 UTC, rrenkert requested changes
Can we detect the state of livestream, applause icon and virtual helpdesk icon? The empty space if none of them are visible looks broken.
A bottom border on the last element does not look like a broken item if the icons/livestream window are present.

2023-08-28 12:17 UTC, Elblinator commented
like raimund said, the bottom border and the additional space should only be present if the livestream window is activated, but they should be both present for-list views.



this is how a singular setting-page looks like if the livestream is present:
![Screenshot_20230828_135839](https://github.com/OpenSlides/openslides-client/assets/69210919/ae232523-6a63-4ee4-b405-c6a8daa35bca)

every mat-card should end and then have a margin to the end of the page (independent of the live stream) 
Example:
![Screenshot_20230828_141308](https://github.com/OpenSlides/openslides-client/assets/69210919/8164777d-ca28-46a1-8b94-196bec1b898d)

2023-09-05 10:02 UTC, rrenkert requested changes
List views look good so far.
Following pages still have no space for the livestream:
* Welcome/Home page
* Autopilot
* Motion overview in tile view
* Motion detail and create
* Tag list
* Agenda - Topic detail
* Agenda - sort
* Election detail
* Participant detail
* File upload
* Projector overview (on small screens)
* Projector detail
* History
* Settings in mobile view 
* Imports

2023-09-07 10:51 UTC, luisa-beerboom commented
> List views look good so far. Following pages still have no space for the livestream:

*only happens in chrome

2023-09-08 08:52 UTC, Elblinator commented
Following pages still have no space for the livestream:

- when creating an amendment the first page
- the tag-list
- the filter "dialog" (especially in motions)

2023-09-08 10:26 UTC, luisa-beerboom commented
> Following pages still have no space for the livestream:
> 
>     * when creating an amendment the first page
> 
>     * the tag-list
> 
>     * the filter "dialog" (especially in motions)

done

2023-09-08 10:34 UTC, bastianjoel requested changes

2023-09-08 10:34 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
> -                        class="paragraph-scroll"
It might not be a good idea to remove this.

2023-09-13 14:09 UTC, rrenkert requested changes

2023-09-13 14:09 UTC, rrenkert commented on client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
> +                <div class="spacer-bottom-60">
Seems to be the wrong container for the spacer. This one creates a second scrollbar on smaller screens.
Tested in brave (chromium based).

2023-09-15 12:12 UTC, luisa-beerboom commented
Had to revert the meeting part of #2230, please check if there are weird scrolling bugs anywhere in the meeting

2023-09-19 12:20 UTC, rrenkert approved these changes

2023-09-26 14:34 UTC, merged