Elections-poll and topic-poll change
OpenSlides/openslides-client pull request #2442
Opened 2023-06-22 08:21 UTC by Elblinator

closes #2323

2023-06-29 12:48 UTC, luisa-beerboom requested changes

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
> +                ) {
Again: Check for empty votes

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
> +    <div *ngIf="!canStillVote()" class="centered-button-wrapper margin-top">
see above

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.html
> +            (click)="submitVotes(delegations)"
Why are you only submitting for the delegations? what about the main vote?

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
> +            pollMaximum *= users.length;
Why are you multiplying the max votes by the number of users?

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
> +            if (!this.hasAlreadyVoted() && !(this.getVotingError() === `You do not have the permission to vote.`)) {
Also: Why are you only checking for one of the possible voting errors?

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
> +    }
This `submitVotes` method is also too long.

Also given that the gist of what the `submitVotes` methods do should be the same for all three poll types, why not try to move this function into the `base-poll-vote.component.ts`. If there are variations, you could encase them into their own helper functions that you can override in the subclasses.

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
> +    }
Please try moving this into the base class as well

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.html
> +            (click)="submitVotes(delegations)"
again: Why only for the delegations?

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
> +        }
Motion polls don't have global options, delete this if clause

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
> +            }
Delete this part, motion polls can only be method `YNA`, so only the else clause of this will ever happen

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
> +    }
Again: Too long and unify this with the others via the base class

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
> +    }
delete

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/components/motion-poll-vote/motion-poll-vote.component.ts
> +    }
see above

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
> +            if (!this.hasAlreadyVoted() && !(this.getVotingError() === `You do not have the permission to vote.`)) {
Another also: You should probably check if deliveringVote for this user is true.
If it is, that is an indication that the operator has already submitted his vote for this user, but that the confirmation has not yet been received, i.e. that you'd be sending a duplicate vote if you send one in this circumstance.
```suggestion
            if (!this.hasAlreadyVoted() && !(this.getVotingError() === `You do not have the permission to vote.` && !this.isDeliveringVote[this.user.id)) {
```

Same for the delegations of course

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
> +        }
```suggestion
        for (let delegation of delegations.concat(this.user) {
            if (!(this.getVotingError(delegation) === `You do not have the permission to vote.`)) {
                if (!this.hasAlreadyVoted(delegation)) {
                    if (this.getVotesCount(delegation) < minVote) {
                        reachedMinValue = true;
                    }
                }
            }
        }
```

Skip the if clause by concatenating the operator user to the delegations and looping through that. You're doing the same thing in both clauses anyway.

You should probably also do this in the other places where you loop through the delegation after already having done the same thing for the operator user beforehand

2023-06-29 12:48 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.html
> +            (click)="submitVotes(delegations)"
Why only the delegations? Why are you even using them as a parameter for this `submitVotes` method? They're saved in the component, right? No need to pass them through the template, just get them within the method.

2023-07-05 09:10 UTC, luisa-beerboom requested changes

2023-07-05 09:10 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
> +                countableDelegations += 1;
```suggestion
                countableDelegations++;
```

2023-07-05 09:10 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
>          }
topic polls also don't have global options, therefore you can delete this

2023-07-06 13:18 UTC, luisa-beerboom requested changes

2023-07-06 13:18 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/modules/poll/base/base-poll-vote.component.ts
> +        for (let delegation of this.delegations) {
There's still better ways to do this

2023-07-06 13:18 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-vote/topic-poll-vote.component.ts
> +    protected getActionButtonClass(actions: VoteOption, option: ViewOption, user: ViewUser = this.user): string {
I believe this is called in the template. Does that still work if this is protected?

2023-07-06 13:18 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/assignments/modules/assignment-poll/components/assignment-poll-vote/assignment-poll-vote.component.ts
> +        const boo = this.poll.isMethodY && this.poll.max_votes_per_option > 1 && !this.isGlobalOptionSelected(user);
Don't call variables things like `boo`. Others won't be able to guess the intent behind them.

2023-07-12 13:29 UTC, luisa-beerboom approved these changes

2023-07-26 07:20 UTC, luisa-beerboom commented
Why change the start script?

2023-07-26 13:30 UTC, Elblinator commented
> Why change the start script?

Ths disabled host-check is only for the dev environments. I accidentically commited it with my other changes. 
When I realised it I removed it.

2023-07-27 14:20 UTC, Elblinator commented
Now the general abstain button is visible in the Y/N voting

2023-07-27 14:32 UTC, m-schieder approved these changes

2023-08-14 08:52 UTC, emanuelschuetze commented
as discussed: we won't integrate this PR -> closed.

2023-08-14 08:52 UTC, closed without merging