Fix broken participant creation if vote_weight enabled
OpenSlides/openslides-client pull request #2450
Opened 2023-06-23 12:45 UTC by luisa-beerboom

Closes #2448

2023-06-23 12:54 UTC, Elblinator approved these changes
code-review

2023-06-26 06:53 UTC, emanuelschuetze requested changes
Save button is now available but the vote weight form field is not visible!

2023-06-26 08:59 UTC, Elblinator approved these changes

2023-06-26 11:03 UTC, emanuelschuetze approved these changes

2023-06-26 11:52 UTC, merged