Testing add util tests
OpenSlides/openslides-client pull request #2492
Opened 2023-07-04 15:29 UTC by luisa-beerboom

TODO: In functions.ts: tests after isEmpty still missing

2023-07-05 13:22 UTC, bastianjoel requested changes

2023-07-05 13:22 UTC, bastianjoel commented on client/src/app/infrastructure/utils/functions.ts
> +        if (a == null) {
Did you mean `b === null`?

2023-07-05 13:46 UTC, luisa-beerboom commented on client/src/app/infrastructure/utils/functions.ts
> +        if (a == null) {
No

2023-07-10 07:12 UTC, bastianjoel approved these changes

2023-07-10 07:16 UTC, merged