Save sort order only on change
OpenSlides/openslides-client pull request #2517
Opened 2023-07-12 14:54 UTC by luisa-beerboom

Closes #2166

2023-07-13 10:27 UTC, Elblinator approved these changes
code-review

2023-08-14 08:51 UTC, emanuelschuetze requested changes
Please follow all admin changes if user is in motion list and on default sorting

2023-08-15 06:11 UTC, Elblinator approved these changes
code-review

2023-08-15 14:42 UTC, emanuelschuetze requested changes
admin changed default sorting -> for all users (also for users with custom sorting) the sorting changed to default.

2023-08-16 11:32 UTC, bastianjoel requested changes

2023-08-16 11:32 UTC, bastianjoel commented on client/src/app/site/base/base-sort.service/base-sort-list.service.ts
> +        return a.length === b.length && a.every((value, index) => value === b[index]);
```suggestion
        return a.equals(b);
```

2023-08-16 11:37 UTC, Elblinator approved these changes
last commit code-review

2023-08-16 11:56 UTC, bastianjoel approved these changes

2023-08-16 14:31 UTC, bastianjoel approved these changes

2023-08-17 15:10 UTC, luisa-beerboom commented
@emanuelschuetze please test if this also fixes #2650 
Given that the last commit should have introduced some stability, I believe it might actually fix it as well

2023-08-18 06:23 UTC, Elblinator approved these changes
code-review

2023-08-28 07:08 UTC, emanuelschuetze approved these changes

2023-08-28 07:10 UTC, merged