Created CommaSeparatedListingComponent for enumerations in html template
OpenSlides/openslides-client pull request #2603
Opened 2023-08-08 14:26 UTC by luisa-beerboom

Closes #2500 

Currently only fixes the agenda item tags, all other places still need to be fixed

2023-08-11 07:47 UTC, bastianjoel approved these changes

2023-08-14 08:11 UTC, emanuelschuetze requested changes
Looks good. One remark in motion pdf where an additional ":" is used:

Motion PDF shows "Zeile 2: (Änderungsempfehlung"):
![motion-pdf](https://github.com/OpenSlides/openslides-client/assets/2075427/dcca423e-0941-48db-b345-e33bed80afc5)

Motion detail shows "Zeile 2 (Änderungsempfehlung)":
![motion-detail](https://github.com/OpenSlides/openslides-client/assets/2075427/92ddd45b-688d-43a7-8ae1-a56dd5e778e8)

Please remove the ":" in motion pdf - motion detail and pdf should contain the the same layout/string(s).

2023-08-14 09:36 UTC, Elblinator approved these changes

2023-08-14 13:48 UTC, bastianjoel approved these changes

2023-08-15 14:36 UTC, merged