Fix personal note UI
OpenSlides/openslides-client pull request #2689
Opened 2023-08-22 12:02 UTC by luisa-beerboom

Closes #2621

2023-08-23 07:42 UTC, bastianjoel approved these changes

2023-08-23 09:52 UTC, Elblinator approved these changes
function

2023-08-23 10:55 UTC, bastianjoel requested changes

2023-08-23 10:55 UTC, bastianjoel commented on client/tests/integration/meeting/motion/history.spec.ts
This should not be included

2023-08-23 13:41 UTC, luisa-beerboom commented on client/tests/integration/meeting/motion/history.spec.ts
Why not?

2023-08-23 14:00 UTC, bastianjoel commented on client/tests/integration/meeting/motion/history.spec.ts
It is unrelated to the issue. We could make another PR where we do a full cleanup of those. Maybe we could also add the test directory to the cleanup command.

2023-08-24 07:48 UTC, bastianjoel approved these changes

2023-08-24 07:49 UTC, merged