Fix topic title
OpenSlides/openslides-client pull request #2690
Opened 2023-08-22 14:57 UTC by luisa-beerboom

Closes #2646

2023-08-23 07:26 UTC, bastianjoel requested changes

2023-08-23 07:26 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/agenda/agenda.subscription.ts
> +            `agenda_item_id`
```suggestion
            { idField: `agenda_item_id`, fields: [`item_number`] }
```

2023-08-23 07:55 UTC, bastianjoel approved these changes

2023-08-24 07:48 UTC, Elblinator commented
The number should be included everywhere 

Can you indicate in a comment or a commit where the numbering would be in included?

2023-08-25 11:58 UTC, bastianjoel approved these changes

2023-08-31 14:19 UTC, Elblinator approved these changes

2023-08-31 15:34 UTC, rrenkert submitted a review, later dismissed
Number and title are now visible in projector and PDF export so works as expected.

2023-08-31 15:34 UTC, rrenkert commented on client/src/app/site/pages/meetings/view-models/base-projectable-model.ts
> +        console.log(`PROJECTOR TITLE!!!`, this);
Cleanup

2023-09-01 13:17 UTC, merged