Enable user count for meeting admins
OpenSlides/openslides-client pull request #2713
Opened 2023-08-28 10:05 UTC by luisa-beerboom

Client pendant to OpenSlides/openslides-autoupdate-service#761
Needs said autoupdate PR to work

2023-08-28 10:09 UTC, bastianjoel approved these changes

2023-08-30 10:51 UTC, Elblinator requested changes
Missing autoupdate when the participant's group changes.
For the statistics to appear/vanish you have to reload.
The statistics are still functional while they are wrongly displayed

2023-08-31 14:02 UTC, luisa-beerboom commented
> Missing autoupdate when the participant's group changes. For the statistics to appear/vanish you have to reload. The statistics are still functional while they are wrongly displayed

Can't replicate

2023-08-31 14:07 UTC, Elblinator approved these changes

2023-08-31 14:17 UTC, merged