Fix single option chart table style
OpenSlides/openslides-client pull request #2774
Opened 2023-09-08 09:23 UTC by luisa-beerboom

Closes #2499

2023-09-08 09:51 UTC, bastianjoel approved these changes

2023-09-08 10:35 UTC, Elblinator requested changes
If all vote amounts are <10: the percent is in two lines between 556px and 465px width
If at least one vote amount is >=10: the percent is in two lines between 1335px and 965px width

The percentage should stay in one line

2023-09-08 12:16 UTC, luisa-beerboom commented
Fixed that. Also changed the motion detail view layout a bit so the table won't flow out of bounds if the card gets to small.

2023-09-11 05:46 UTC, Elblinator approved these changes
function

2023-09-11 07:04 UTC, bastianjoel approved these changes

2023-09-11 07:05 UTC, merged