Make motion multiselect csv export sort by current sorting
OpenSlides/openslides-client pull request #2783
Opened 2023-09-11 09:57 UTC by luisa-beerboom

Closes #2780

2023-09-11 10:46 UTC, bastianjoel approved these changes

2023-09-11 12:08 UTC, emanuelschuetze requested changes
* should also work for amendment-list
* change amendment-list default sorting to main-motion-and-linenumber

2023-09-11 14:12 UTC, emanuelschuetze requested changes
amendment list does not work -> always the same order in pdf export (by id)

2023-09-12 06:33 UTC, Elblinator approved these changes
Code

2023-09-12 06:33 UTC, merged