Fix theme subscription
OpenSlides/openslides-client pull request #2812
Opened 2023-09-15 14:37 UTC by luisa-beerboom

Closes #2768

2023-09-18 11:12 UTC, bastianjoel requested changes

2023-09-18 11:12 UTC, bastianjoel commented on client/src/app/site/pages/organization/pages/designs/pages/design-main/components/design-main/design-main.component.ts
> +        this.updateSubscribeTo(getDesignListSubscriptionConfig());
This is reopening the subscription every time one accesses the design list. We do not want this.

2023-09-20 09:29 UTC, luisa-beerboom commented
I looked into it again:
By superficially removing the cdk scroll viewport logic from the scrolling table components template and replacing it with a regular ngFor, I was able to stop it from displaying that behaviour.
So it seems to have something to do with the scroll viewport or its handling.

I'll see what I can do about it

2023-09-26 08:11 UTC, bastianjoel approved these changes

2023-09-26 08:12 UTC, bastianjoel commented
Please update the title of the PR

2023-09-26 14:47 UTC, rrenkert approved these changes

2023-09-27 12:43 UTC, merged