Add filter for gender in participant list.
OpenSlides/openslides-client pull request #2813
Opened 2023-09-16 09:00 UTC by rrenkert

2023-09-16 09:56 UTC, emanuelschuetze approved these changes

2023-09-21 19:27 UTC, emanuelschuetze commented
@rrenkert feel free to merge this PR or split out in separate PR.

2023-09-26 14:57 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
> +                                .filter((v, i, a) => a.findIndex(v2 => v2 === v) === i)
What's this supposed to do?

2023-09-27 13:27 UTC, luisa-beerboom requested changes

2023-09-27 13:27 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
> +                                .filter((v, i, a) => a.findIndex(v2 => v2 === v) === i)
```suggestion
                            group_ids: [...new Set(nextGroupIds.concat(chosenGroupIds))]
```

2023-09-27 15:05 UTC, luisa-beerboom approved these changes

2023-09-28 14:16 UTC, merged