Fix motion list structure level
OpenSlides/openslides-client pull request #2828
Opened 2023-09-21 12:14 UTC by luisa-beerboom

Closes #2827

2023-09-21 14:46 UTC, emanuelschuetze requested changes
structure level and number is still missing in some views:
* autopilot (LoS, assignment poll)
* assignment-detail (candidate list, assignment poll)

2023-09-21 15:44 UTC, rrenkert commented
> structure level and number is still missing in some views:
> 
> * autopilot (LoS, assignment poll)
> * assignment-detail (candidate list, assignment poll)

This is not part of the issue nor the PR!

2023-09-21 15:57 UTC, bastianjoel requested changes

2023-09-21 15:57 UTC, bastianjoel commented on client/src/app/gateways/repositories/meeting_user/meeting-user-repository.service.ts
We do not want to add new fieldsets because within the subscriptions we do not have any direct reference to these and therefore cannot see which fields will be subscribed.

2023-09-21 15:57 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
> +                                        fieldset: [...UserFieldsets.FullNameSubscription.fieldset, `meeting_user_ids`]
Unnecessary subscription to meeting user ids should be prevented. Removing this can be tracked in #2789.

2023-09-21 15:58 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/motions.subscription.ts
> +                                        fieldset: [...UserFieldsets.FullNameSubscription.fieldset, `meeting_user_ids`]
Not a change request just a comment.

2023-09-21 20:59 UTC, luisa-beerboom commented
> > structure level and number is still missing in some views:
> > 
> > * autopilot (LoS, assignment poll)
> > * assignment-detail (candidate list, assignment poll)
> 
> This is not part of the issue nor the PR!

I did it anyway, since it's basically a copy-and-paste measure

2023-09-22 12:10 UTC, bastianjoel approved these changes

2023-09-29 13:39 UTC, emanuelschuetze requested changes
The structure level and number of motion supporter was not loaded in motion detail - after reload this page.

2023-09-29 14:08 UTC, emanuelschuetze approved these changes

2023-09-29 14:25 UTC, merged