Remove paginator from history page
OpenSlides/openslides-client pull request #2882
Opened 2023-10-12 08:35 UTC by reiterl

Closes #2875

2023-10-12 09:11 UTC, bastianjoel approved these changes

2023-10-20 14:11 UTC, Elblinator approved these changes
function

2023-10-20 14:12 UTC, bastianjoel requested changes
The `MatPaginatorModule` should also be remove from `history.module.ts`

2023-10-23 08:29 UTC, reiterl commented
Ah, okay. I have removed the pagenator from the history module. Missed that.

2023-10-24 07:48 UTC, merged