Account import improvements
OpenSlides/openslides-client pull request #2919
Opened 2023-10-19 14:59 UTC by luisa-beerboom

Closes #2894

2023-10-20 13:38 UTC, bastianjoel approved these changes

2023-10-23 09:22 UTC, Elblinator requested changes
A) vote weight as short as possible
B) Please change textt to "Accounts with warnings: the affected cells will be skipped: 
D)"
 1) one space to much in helper-box
 2) Please change in the preview "Gender, possible options: male, female, diverse, non-binary" to only "Gender"

2023-10-23 12:54 UTC, Elblinator requested changes

2023-10-23 12:54 UTC, Elblinator commented on client/src/app/site/pages/organization/pages/accounts/pages/account-import/services/account-import.service/account-import.service.ts
> +        warning: _(`Accounts with warnings (affected cells will be skipped)`)
warning: _(`Accounts with warnings: affected cells will be skipped`)

2023-10-27 07:46 UTC, bastianjoel approved these changes

2023-11-10 11:29 UTC, Elblinator approved these changes

2023-11-10 11:29 UTC, merged