Change duration of request of speakers to hours:mins
OpenSlides/openslides-client pull request #2948
Opened 2023-10-25 12:48 UTC by reiterl

Closes #2942 
Update duration service.

2023-10-26 09:03 UTC, Elblinator approved these changes
function

2023-10-27 07:18 UTC, bastianjoel requested changes

2023-10-27 07:18 UTC, bastianjoel commented on client/src/app/site/services/duration.service.ts
The method description should be updated to `Calculates a given time to a readable string, that contains hours and minutes.`

2023-10-27 07:18 UTC, bastianjoel commented on client/src/app/site/services/duration.service.ts
>          if (!isNaN(+minutes) && !isNaN(+seconds)) {
Seconds is not needed anymore. 

```suggestion
        const minutes = `0${Math.floor((duration % 3600) / 60)}`.slice(-2);
        if (!isNaN(+minutes)) {
```

2023-10-27 11:47 UTC, reiterl commented on client/src/app/site/services/duration.service.ts
done.

2023-10-27 11:47 UTC, reiterl commented on client/src/app/site/services/duration.service.ts
>          if (!isNaN(+minutes) && !isNaN(+seconds)) {
done.

2023-10-27 12:34 UTC, bastianjoel approved these changes

2023-11-01 07:00 UTC, Elblinator approved these changes
function

2023-11-01 07:01 UTC, merged