Add missing sorting for filter properies in filter list
OpenSlides/openslides-client pull request #2953
Opened 2023-10-26 11:28 UTC by reiterl

Closes #2939

Sort the filterProperties by the label which is trimed

2023-10-27 07:11 UTC, bastianjoel requested changes

2023-10-27 07:11 UTC, bastianjoel commented on client/src/app/site/base/base-filter.service/base-filter-list.service.ts
> +                            .sort(sortFn);
No need to declare the sort function somewhere else. 

```suggestion
                            .sort((a, b) => a.label.trim().localeCompare(b.label.trim()));
```

2023-11-01 09:46 UTC, bastianjoel approved these changes

2023-11-02 07:11 UTC, Elblinator approved these changes
function

2023-11-02 07:11 UTC, merged