Fix a problem in the poll service
OpenSlides/openslides-client pull request #2963
Opened 2023-10-30 10:46 UTC by reiterl

Closes #2914 

An array is an reference type and can be changed. So copy the array helps.

2023-11-01 07:31 UTC, Elblinator requested changes
Please also add default groups for motion-votes and agenda-votes

2023-11-01 09:22 UTC, reiterl commented
Add the fix to the two other poll services.

2023-11-01 10:37 UTC, Elblinator approved these changes
function

2023-11-02 14:31 UTC, bastianjoel approved these changes

2023-11-03 06:55 UTC, merged