Update los contribution count
OpenSlides/openslides-client pull request #2968
Opened 2023-11-02 08:11 UTC by reiterl

Update the hasSpokenCount method. Point of Order should not be counted as contribution.

Closes #2959

2023-11-02 11:53 UTC, Elblinator approved these changes
function

2023-11-02 14:26 UTC, bastianjoel requested changes

2023-11-02 14:26 UTC, bastianjoel commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
> +            .filter(finishedSpeaker => !finishedSpeaker.point_of_order).length;
```suggestion
            .filter(finishedSpeaker => finishedSpeaker.user_id === speaker.user_id && !finishedSpeaker.point_of_order).length;
```

2023-11-03 08:24 UTC, reiterl commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
> +            .filter(finishedSpeaker => !finishedSpeaker.point_of_order).length;
done.

2023-11-03 09:29 UTC, Elblinator approved these changes

2023-11-03 09:29 UTC, merged