motion block update place of recommender
OpenSlides/openslides-client pull request #2989
Opened 2023-11-07 08:56 UTC by reiterl

Closes #2924

2023-11-07 10:33 UTC, Elblinator requested changes
please also add the class "spacer-top-3" to the div

the motion-list also uses this class at this place

2023-11-07 12:34 UTC, reiterl commented
done

2023-11-08 11:09 UTC, bastianjoel approved these changes

2023-11-10 11:28 UTC, Elblinator approved these changes

2023-11-10 11:29 UTC, merged