Global search improvements
OpenSlides/openslides-client pull request #3013
Opened 2023-11-15 12:17 UTC by bastianjoel

- Display results found via change reco or poll
- Fix mediafile folder urls
- Display preview and mark match in amendments

2023-11-21 15:07 UTC, luisa-beerboom approved these changes

2023-11-22 07:21 UTC, Elblinator requested changes
Folders are not detectable: {"message":"Media-Server: Not Found."}

Amendments are not detectable at all.

2023-11-22 08:23 UTC, bastianjoel commented
Sounds like you are using an old version of the search service.

2023-11-22 09:27 UTC, Elblinator approved these changes

2023-11-22 09:43 UTC, merged