Fix multiselect motion move in agenda
OpenSlides/openslides-client pull request #3036
Opened 2023-11-21 15:28 UTC by bastianjoel

resolves #3019

2023-11-22 07:36 UTC, Elblinator requested changes
if a motion is added via multiselect then the visibility is always hidden. -> the visibility should follow the pre determined default visibility (see settings > default visibility for new agenda items)

2023-11-22 08:37 UTC, bastianjoel commented
Not moving the motion when it is already in the agenda would change the current behavior. I think this should be discussed and has nothing to do with this fix so please open another issue for that.

2023-11-22 09:39 UTC, Elblinator approved these changes
function

2023-11-23 08:53 UTC, luisa-beerboom approved these changes

2023-11-23 08:53 UTC, merged