Implement participant import via backend
OpenSlides/openslides-client pull request #3044
Opened 2023-11-24 10:25 UTC by luisa-beerboom

Closes #2670 

Needs OpenSlides/openslides-backend#1980 to work

2023-11-24 12:39 UTC, bastianjoel approved these changes

2023-12-06 13:59 UTC, Elblinator requested changes
The icon "autorenew" icon is shown but there is not explanation why or what consequenses this has, e.g. when the example-file is imported

If a participant belongs to only one group and this group is not found then there is an unexplained "+1" and the group-name is too far up 

If a participant has more than one group then only one group is displayed, there is an unexplained "+1" and the name is too far up

Please change the title "saml_id" to "SAML ID"

2023-12-08 09:27 UTC, Elblinator commented
> Please be more precise on where this is inappropriately shown, as there are some places (f.E. the title row of the actual csv file) where this wording is absolutely required by our technical system

Please change the string "saml_id" in the preview to "SAML ID"

2023-12-08 14:05 UTC, bastianjoel approved these changes

2023-12-08 14:06 UTC, merged