Disable save button and change warning for too small vote_weight
OpenSlides/openslides-client pull request #3060
Opened 2023-11-30 10:18 UTC by Elblinator

closes #3058

2023-12-05 07:51 UTC, bastianjoel requested changes

2023-12-05 07:51 UTC, bastianjoel commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.ts
I don't think the changes in this file are needed.

2023-12-05 07:51 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts
> +    public form: UntypedFormGroup;
`form` seems to be defined by the `ng-template`. So no need to add this here.

2023-12-05 11:14 UTC, bastianjoel approved these changes

2023-12-09 14:22 UTC, emanuelschuetze commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
> +                        Please select a vote weight greater than or equal 0.000001
"... or equal _to_ ..." -> missing word

2023-12-10 13:57 UTC, emanuelschuetze commented
New translations of upstream/main contains also the new strings of this PR. But please fix the remark (missing "to") which I've fixed locally for my translation work.

2023-12-11 13:40 UTC, MSoeb approved these changes

2023-12-12 06:43 UTC, merged