Add tests to lifecycle service
OpenSlides/openslides-client pull request #3075
Opened 2023-12-08 10:38 UTC by reiterl

Add some tests to the lifecycle service with StorageService mockup.

2023-12-12 09:03 UTC, bastianjoel requested changes

2023-12-13 13:45 UTC, reiterl commented on client/src/app/site/services/lifecycle.service.spec.ts
> +        expect(service.isBooted).toBe(true);
Mmh, I have worked at the tests. I moved the reset and reboot parts into own test cases and use the test the emitter in them.

2023-12-13 13:45 UTC, reiterl commented on client/src/app/site/services/lifecycle.service.spec.ts
> +        expect(shutdowned).toBe(true);
s.o.

2023-12-14 12:10 UTC, bastianjoel approved these changes

2023-12-14 12:10 UTC, merged