Update mdc snackbar
OpenSlides/openslides-client pull request #3097
Opened 2023-12-12 12:04 UTC by bastianjoel

part of #2934

2023-12-13 11:46 UTC, Elblinator requested changes
in darkmode: progress bar looks always completely filled

in darkmode: in a snackbar can the text color be as dark as is was before?

2024-03-08 11:26 UTC, jsangmeister commented
@bastianjoel please resolve conflicts

2024-03-08 14:53 UTC, Elblinator commented
Is this PR really ready for review= Is my CR fixed? 
Please assign me accordingly

2024-03-12 10:55 UTC, bastianjoel commented
> in darkmode: in a snackbar can the text color be as dark as is was before?

I would just stick with the default there.

2024-03-12 13:12 UTC, Elblinator approved these changes

2024-03-12 14:06 UTC, bastianjoel commented on client/src/assets/styles/theme-styles.scss
>      @include mat.all-legacy-component-themes($openslides-light-theme);
We need to wait until all components are migrated.

2024-03-12 14:07 UTC, merged