Fix linter warnings
OpenSlides/openslides-client pull request #3103
Opened 2023-12-14 14:57 UTC by Elblinator

closes #3079

2024-02-01 17:23 UTC, jsangmeister commented
ping @rrenkert @bastianjoel

2024-02-06 09:59 UTC, bastianjoel approved these changes

2024-02-15 15:22 UTC, rrenkert requested changes
Metting->Settings is available via `enter` the backspace navigation is missing but should be availbale.
File-list is lacking the navigation to edit dialog via row item 'groups'

2024-02-22 08:28 UTC, bastianjoel commented on client/src/app/ui/modules/file-list/components/file-list/file-list.component.ts
> +    public isInaMeeting = true;
```suggestion
    public isInMeeting = true;
```

2024-03-11 10:21 UTC, Elblinator commented
> Metting->Settings is available via enter the backspace navigation is missing but should be availbale.
You can navigate back with alt + arrow left and you do not need tab to navigate back

2024-03-15 10:43 UTC, rrenkert approved these changes

2024-03-15 14:02 UTC, merged