add Moderator Note
OpenSlides/openslides-client pull request #3113
Opened 2023-12-20 14:42 UTC by Elblinator

2024-01-16 11:44 UTC, bastianjoel requested changes
Unfinished. I don't think we should merge this in its current state.

2024-01-16 11:44 UTC, bastianjoel commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
> +    private _contentObject = this._listOfSpeakers?.content_object;
Add type.

2024-01-18 14:03 UTC, bastianjoel commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.html
> +<mat-card class="spacer-bottom-60" [ngClass]="isEditing ? 'os-form-card' : 'os-card'" *ngIf="canSeeModerationNote">
I don't think it makes sense to display an empty moderation note if the user cannot edit it. 

```suggestion
<mat-card class="spacer-bottom-60" [ngClass]="isEditing ? 'os-form-card' : 'os-card'" *ngIf="canSeeModerationNote && (canManageModerationNote || (moderatorNotes | async))">
```

2024-01-19 07:53 UTC, luisa-beerboom approved these changes

2024-01-19 07:53 UTC, luisa-beerboom commented
Code LGTM

2024-01-19 09:03 UTC, merged