Clean up several constructors
OpenSlides/openslides-client pull request #3119
Opened 2023-12-22 13:21 UTC by Elblinator

2024-01-09 08:25 UTC, bastianjoel requested changes

2024-01-09 08:25 UTC, bastianjoel commented on client/src/app/gateways/export/csv-export.service/csv-export.service.ts
`inject` should only be used when needed. Using the constructor is still the default way to add services.

2024-01-09 15:26 UTC, closed without merging

2024-01-10 06:51 UTC, Elblinator commented
this PR is closed due to the false base and too many change recommendations 
see #3129

2024-01-10 07:18 UTC, jsangmeister commented
Just FYI, you can simply change the base by clicking the "edit" button next to the title ;)