Remove default number from user
OpenSlides/openslides-client pull request #3127
Opened 2024-01-08 10:55 UTC by reiterl

Remove the `default_number` code.
Closes #3030

2024-01-09 08:58 UTC, bastianjoel approved these changes

2024-01-15 08:51 UTC, Elblinator requested changes
please remove the Default number input in the account detail view (account-detail.component.html

2024-01-22 08:13 UTC, Elblinator approved these changes
function

2024-01-23 11:27 UTC, bastianjoel approved these changes

2024-01-23 11:27 UTC, merged