Add preamble to motion edit view
OpenSlides/openslides-client pull request #3140
Opened 2024-01-12 12:49 UTC by luisa-beerboom

Closes #3059

2024-01-15 12:01 UTC, Elblinator requested changes
please remove the star if the reasons is required and the preamble should not be translated

2024-01-18 14:13 UTC, bastianjoel requested changes

2024-01-18 14:13 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.html
> +        <h3>
You might want to check if a preamble is set. 

```suggestion
        <h3 *ngIf="showPreamble && preamble">
```

2024-01-24 12:17 UTC, bastianjoel approved these changes

2024-02-01 12:42 UTC, Elblinator approved these changes

2024-02-01 12:43 UTC, Elblinator commented
LGTM but please fix linting

2024-02-02 11:03 UTC, merged