List of speakers export
OpenSlides/openslides-client pull request #3163
Opened 2024-01-19 13:37 UTC by bastianjoel

resolves #3156

We might need to discuss if the exported data is sufficient. 

Also I would stress that it might make sense to move the page to the agenda as I think that LOS is more related to the agenda then to participants.

2024-01-22 10:14 UTC, luisa-beerboom reviewed
I haven't found anything to complain about concerning code style, however I can't go further in my review, since neither the PR description nor the title tell me what exactly this PR is supposed to achieve. There is also no issue linked. Please rectify that.

2024-01-22 13:14 UTC, Elblinator requested changes
The title-columns in the CSV-file should be changed
- The Name column should be splitted into three columns (Title, first name ans surnam)
- an additional row for the participant number should be added
- The naming for the Name column should change (in order from left to right) = Title,  First name, Surname, Structure level, Participant number, Speech-Type, Time, Element

The file-name should be changed to lists_of_speakers.csv

Updated 22.01.24 15:35

2024-01-22 15:36 UTC, luisa-beerboom approved these changes

2024-01-24 07:52 UTC, luisa-beerboom approved these changes

2024-01-24 14:17 UTC, Elblinator approved these changes
function

2024-01-24 14:17 UTC, merged