Export speaker agenda item number
OpenSlides/openslides-client pull request #3223
Opened 2024-01-30 10:08 UTC by bastianjoel

resolves #3220

2024-01-30 10:47 UTC, jsangmeister approved these changes

2024-01-31 11:17 UTC, MSoeb requested changes
Prefix is corrected correctly, but there is an Autoupdate error:

If the data is exported without opening the agenda menu first, the prefixes won't be exported. 

Repro:
0. An instance with existing data in the agenda is needed.
1. open participants without opening the agenda first > three dot menu > contributiions > export the data. prefixes are not exported.
2. open agenda and do step 1. again. -> prefixes are exported.

2024-02-06 12:49 UTC, rrenkert approved these changes

2024-02-06 14:15 UTC, emanuelschuetze approved these changes

2024-02-06 14:15 UTC, merged