Fix user edit for illegal legacy username
OpenSlides/openslides-client pull request #3254
Opened 2024-02-03 14:31 UTC by luisa-beerboom

Closes #3250 

Should filter out most unchanged keys if it is an update, please check if this breaks _any_ field in account or participant edit.
Also check for create nothing should be changed.
Also check what happens if you edit a user, save, and then edit again.

This PR _should_ also make it possible to save even if a legacy username with empty spaces is left unchanged in the preview.

2024-02-03 14:33 UTC, bastianjoel approved these changes

2024-02-03 15:05 UTC, Elblinator requested changes
if you create a new participant and fill any of the four fields from step 1 (Given name, last name, email or username) then these values are not send in the payload from step 3 (creation) 
The values have to be re entered/change/ not pristine to be send in the payload

2024-02-03 15:35 UTC, Elblinator approved these changes
function

2024-02-03 15:39 UTC, bastianjoel approved these changes

2024-02-03 16:22 UTC, luisa-beerboom commented
Merging ist @peb-adr s responsibility

2024-02-08 16:53 UTC, peb-adr commented
Merging into `stable/4.1.x`.
New workflow for this is described in wiki:
https://github.com/OpenSlides/OpenSlides/wiki/Update-Workflow#hotfixes

2024-02-08 16:53 UTC, merged