Move ICC to shared worker
OpenSlides/openslides-client pull request #3276
Opened 2024-02-13 12:36 UTC by bastianjoel

resolves #3248

2024-03-11 15:32 UTC, luisa-beerboom requested changes
Beside the other things, I saw multiple constructors without visibility modifiers, please change that

2024-03-11 15:32 UTC, luisa-beerboom commented on client/src/app/worker/http/auth.ts
> +    private destroy() {
```suggestion
    private destroy(): void {
```

2024-03-11 15:32 UTC, luisa-beerboom commented on client/src/app/worker/http/http-stream.ts
> +    }
Sort declarations by visibility

2024-03-11 15:32 UTC, luisa-beerboom commented on client/src/app/worker/http/http-subscription-polling.ts
> +    }
This method is too long, it should be possible to split it up to improve readability

2024-03-11 15:32 UTC, luisa-beerboom commented on client/src/app/worker/http/http-subscription-sse.ts
> +    }
Too long, please make this shorter

2024-03-11 16:17 UTC, bastianjoel commented
Using accessibility modifiers for constructors is not consistently done. I don't like introducing this rule right now with this PR.

In the future we could think about adding an eslint rule https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md

2024-03-12 11:36 UTC, luisa-beerboom commented
> Using accessibility modifiers for constructors is not consistently done in the client. I don't like introducing this rule right now with this PR.

It is not an introduction, it is overwhelmingly done in the client for the simple reason that it _is_ an established convention to put visibility modifiers on everything, the exceptions where it is inconsistent are merely instances that were not caught during the code review.

2024-03-12 12:33 UTC, luisa-beerboom approved these changes
Or fix this in another PR

2024-03-28 14:05 UTC, bastianjoel commented
@emanuelschuetze @MSoeb @Elblinator @rrenkert Maybe it is not completely obvious by the title and description but this PR includes the longpolling implementation and is finished since last week. 
If anybody is feeling qualified to test this feel free to add a review. 

The [performance tool](https://github.com/OpenSlides/openslides-performance) has a new tool `broken-proxy` to test this.

2024-04-03 13:33 UTC, rrenkert requested changes
Works as expected.

But the warning sign is not centered:

![image](https://github.com/OpenSlides/openslides-client/assets/19685715/0c2c735c-d868-4c7c-a3eb-3397ea559477)

2024-04-03 13:37 UTC, bastianjoel commented
>:(

2024-04-05 08:04 UTC, bastianjoel commented
This is a problem with the banner service. Offline mode and out of sync have the same problem. For that reason I think this is totally unrelated to this PR. Please open another issue.

2024-04-05 10:45 UTC, Elblinator commented
I created a new Issue 
see #3506

2024-04-05 14:21 UTC, merged