Add contributions list content type filter
OpenSlides/openslides-client pull request #3279
Opened 2024-02-13 13:58 UTC by bastianjoel

resolves  #3267

2024-02-13 14:02 UTC, jsangmeister requested changes

2024-02-13 14:02 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/view-models/view-speaker.ts
> +        return this.list_of_speakers?.content_object_id?.split(`/`)[0];
Please use https://github.com/OpenSlides/openslides-client/blob/main/client/src/app/infrastructure/utils/transform-functions.ts#L69

2024-02-13 16:01 UTC, luisa-beerboom requested changes

2024-02-14 09:04 UTC, emanuelschuetze approved these changes

2024-02-14 09:13 UTC, luisa-beerboom approved these changes

2024-02-14 09:14 UTC, merged