Allow to set PoO for others
OpenSlides/openslides-client pull request #3324
Opened 2024-02-20 16:53 UTC by Elblinator

closes #3314

2024-02-21 15:19 UTC, jsangmeister requested changes
You should also update the meta repo & the default setting values

2024-02-21 15:19 UTC, jsangmeister commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-content/list-of-speakers-content.component.ts
> +    public pointOfOrderEnabled = false;
Does not seem like this needs to be public

2024-02-21 15:19 UTC, jsangmeister commented on client/src/app/site/pages/meetings/services/meeting-settings-definition.service/meeting-settings-definitions.ts
> +                        helpText: _(`Requires permission can manage list of speaker`),
either use the technical term `list_of_speakers.can_manage` (probably not, though) or form a full sentence like "Requires permission to manage lists of speakers"

2024-02-22 07:55 UTC, jsangmeister requested changes

2024-02-22 07:55 UTC, jsangmeister commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/modules/point-of-order-dialog/components/point-of-order-dialog/point-of-order-dialog.component.ts
> +        this.operator.userObservable.subscribe(user => (this._currentUser = user)),
```suggestion
        this.operator.userObservable.subscribe(user => (this._currentUser = user));
```
or am I missing something here?

2024-02-22 10:22 UTC, rrenkert requested changes
The user shown in the LoS is always the currently logged in user, not the the selected one.

2024-02-22 10:55 UTC, rrenkert approved these changes

2024-02-22 11:08 UTC, merged