Update mdc dialog
OpenSlides/openslides-client pull request #3397
Opened 2024-03-06 12:33 UTC by Elblinator

part of #2934 

Changed the dialog
The appearance should have slightly changed

2024-03-11 11:58 UTC, bastianjoel requested changes

2024-03-11 11:58 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/modules/topic-poll/components/topic-poll-dialog/topic-poll-dialog.component.html
> +<div mat-dialog-actions class="padding-left-24 padding-top-bottom-16">
I am not sure if we should do this. In my opinion we should just stick to the defaults from mdc as much as possible. 

In future versions the appearance could always change and adding imho unnecessary adaptions should be prevented.

2024-03-11 14:05 UTC, Elblinator commented
The formatting does not wok for client/src/app/site/modules/global-headbar/components/account-dialog/account-dialog.component.scss if the padding:0 is removed 
I would really prefer this padding here

2024-03-11 15:02 UTC, bastianjoel approved these changes

2024-03-15 10:51 UTC, MSoeb approved these changes

2024-03-15 11:10 UTC, merged