Add arrow navigation to topic detail view
OpenSlides/openslides-client pull request #3462
Opened 2024-03-20 09:57 UTC by reiterl

Part of #3447 

Allow in the topic detail view to navigate thru the topics of the meeting.

2024-03-21 16:00 UTC, emanuelschuetze requested changes

2024-03-22 09:01 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.ts
> +        }
Replace the sequential_number with empty string here.
Show only the arrows in the arrow navigation, if there is no number.

2024-03-22 09:03 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +        <div *ngIf="vp.isMobile && showNavigateButtons">
Remove the entries from the menu and always show the arrow navigation in mobile mode.

2024-03-25 07:37 UTC, Elblinator requested changes
- The arrow and the number are on not at the same spot. (For the left arrow) The arrow is further left then the number), please display them at the same spot
- If a topic is loaded and then the person is not allowed to see it anymore then the person is still able to navigate through this topic 
(Reproduction: 1. as deli be allowed to mange the agenda -and therefore see hidden topics- 2. open agenda, 3. take away the right to manage the agenda -hidden topic vanishes- navigate through topics -> you can still see the detail view from the hidden topic

2024-03-25 08:46 UTC, Elblinator requested changes

2024-03-25 08:46 UTC, Elblinator commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +                class="topic-detail-nav-button"
please remove the unused class

2024-03-25 08:46 UTC, Elblinator commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +                class="topic-detail-nav-button"
please remove the unused class

2024-03-25 09:06 UTC, Elblinator commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +        <div *ngIf="!editTopic && showNavigateButtons" class="extra-controls-slot prev-next-topic-controls">
additional unused class

2024-04-04 08:54 UTC, reiterl commented
I need https://github.com/OpenSlides/openslides-backend/issues/2352 for a setting as switch for the agenda item arrow navigation.

2024-04-04 09:14 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +                class="topic-detail-nav-button"
done

2024-04-04 09:14 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +                class="topic-detail-nav-button"
done

2024-04-04 09:15 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/agenda/modules/topics/pages/topic-detail/components/topic-detail/topic-detail.component.html
> +        <div *ngIf="!editTopic && showNavigateButtons" class="extra-controls-slot prev-next-topic-controls">
done

2024-04-04 10:24 UTC, reiterl commented
I updated the sorting of the navigation. I talked with @luisa-beerboom about the problem with deleted agenda items in the `ViewModelListObservable`. It could be a problem with the repository. @bastianjoel  let us talk about it.

2024-04-04 10:24 UTC, reiterl commented
Also I need to introduce the setting logic.

2024-04-09 09:41 UTC, reiterl commented
I have update the services and now the delete topic/still visible is no longer an issue. I cannot reproduce it any longer.
I have talked with @bastianjoel  about is. It needs a test.

Open is the missing setting stuff.

2024-04-09 11:14 UTC, reiterl commented
The show/hide setting  part of this issue will be done in a different issue. Else this feature is complete.

2024-04-09 12:10 UTC, Elblinator requested changes
this is seems to be an unrelated issue <s>a delegate is always able to see hidden topics, hidden topics should only be visible if the participant is allowed to manage the agenda</s>

the arrows are not visible at all if: 
1. navigate to topic view
2. shrink window to mobile view 
3. reload page
4. arrows are not visible
5. arrows stay invisible even if the view is widened

2024-04-09 12:15 UTC, Elblinator commented
maybe look at motion-detail-view.component for a reference for the arrows

2024-04-10 08:40 UTC, bastianjoel approved these changes

2024-04-10 09:19 UTC, merged