LoS UI rework
OpenSlides/openslides-client pull request #3466
Opened 2024-03-21 10:07 UTC by bastianjoel

resolves #3459

2024-03-28 08:08 UTC, Elblinator reviewed
It looks rather nice and feels great to work with so far
two notes: 
1. can you please reduce the margin-top from .current-speaker to 10px? 
The 50px make it look very busy if you activate/deactivate current-speaker a lot
2. I have some other remarks and questions about the design. They should be rather simple but need some conceptual talk. I'll talk with @emanuelschuetze about it then get back to you

it really really cool in my opinion!

2024-04-03 09:18 UTC, Elblinator requested changes
in the list: 
- [x] .current-speaker { martin-top:10px; margin-bottom:0}
- [x] .speaker-name {font-weight: 500}
- [x] the **icons** from pro/contra should have the corresponding colour (green and red, like it was before)
- [x] PoO icon and text should be in the warn colour again
- <s>the text speaker-additional-info and speech-type should be rgba(0, 0, 0, 0.54);</s>
- [x] the middot should only be present if it is needed (add a participant withou any additional information and then activate the star contribution there will be a "icon Contribution middot"
- [x] the first interposed question should have a margin-top:0 and a boder of 1 px which should be transparent if the question is not active and it should be white if the question is active
- [x] every entry should have the same height, even if there is not enough information to fill three lines
- [x] the whole entry ( I think .speaker-info or .single-speaker-line) should have a padding top and bottom of 4px
- <s>please invert the filling from the stop button (see Mock-up)</s>
- [ ] the play buttons for every participant on the waiting list should be slightly smaller
- <s>the  play buttons for every participant on the waiting list (besides the first one) should be greyer (for now please use rgba(0, 0, 0, 0.54);)</s>
- [x] the play button for the first participant on the waiting list should be in accent colour
- [ ] UI for <ins>current</ins> speaker: 
   - [x] remove the "special colour" from pro/contra/PoO/contribution number 
   - [ ] the play button should be at the same placing as the other play buttons (meaning they should be directly under each other)
   - [ ] the os-countdown-time should be bigger
- [ ] Last speakers list: 
    - the word 'start time' should be removed
    - in front of the time should be the icon ' schedule' <s>
    - either 
A) pull the start time back into the os-list-of-speakers-entry (that would be better)
B) revert the visual changes from the list
-> the goal here is to make the list slimmer
other idea to reach that are also welcome</s>


this will be done in future issues: 
 <s>The title-line:
- if a LoS is closed add the lock icon (smaller) right next to the title in a raised manner  (for reference project a LoS onto a projector and close it)
- in the button which closes/opens the LoS: 
   -  make the Lock-icon as a permanent icon (the outlines should be white and the icon should not be filled
   - [x] change the tooltips to "Close list of speakers" and "Open list of speakers"
- change the currently used icon for the re-add button to the "undo" icon</s>

2024-04-03 13:29 UTC, bastianjoel commented
> the play buttons for every participant on the waiting list (besides the first one) should be greyer (for now please use rgba(0, 0, 0, 0.54);)
I don't like this. I would prefer sticking to the colors available by angular material

> the play buttons for every participant on the waiting list should be slightly smaller
Please specify how small exactly. Same as stop button?

> please invert the filling from the stop button (see Mock-up)
Material design icons is lacking a outlined stop button

> Last speakers list
Directly following speakers are currently categorized. I don't like the old design and I would really like to get this unified into the speaker entry. For option A on the other hand we are lacking space there.

2024-04-03 14:03 UTC, bastianjoel commented
> change the currently used icon for the re-add button to the "undo" icon

It is already the undo icon?

2024-04-05 13:25 UTC, Elblinator commented
I edited my change request accordingly to your comments and the discussion

2024-04-09 14:29 UTC, emanuelschuetze approved these changes
Looks good now!

2024-04-10 07:54 UTC, luisa-beerboom approved these changes

2024-04-10 07:54 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.scss
> +    */
?

2024-04-10 07:54 UTC, luisa-beerboom commented on client/src/app/site/pages/meetings/modules/list-of-speakers-content/components/list-of-speakers-entry/list-of-speakers-entry.component.scss
> +    */
See above

2024-04-10 08:36 UTC, merged