Fixes committee export and example import file
OpenSlides/openslides-client pull request #3476
Opened 2024-03-26 10:03 UTC by Elblinator

closes #3475 
and closes #3273

2024-03-26 10:45 UTC, bastianjoel requested changes

2024-03-26 10:45 UTC, bastianjoel commented on client/src/app/domain/models/comittees/committee.constants.ts
Please also rename the vars. Also they are currently only used within that file. So maybe remove the exports while you are at it.

2024-03-26 12:10 UTC, bastianjoel approved these changes

2024-04-08 13:59 UTC, luisa-beerboom approved these changes

2024-04-09 07:54 UTC, rrenkert commented
After testing the export and import for committees we decided to not export the meeting specific data for only the _first_ meeting of a committee since this can lead to faulty (re-)imports.

2024-04-10 07:59 UTC, luisa-beerboom approved these changes

2024-04-24 07:44 UTC, merged