Update mdc cards
OpenSlides/openslides-client pull request #3487
Opened 2024-03-27 08:27 UTC by Elblinator

part of https://github.com/OpenSlides/openslides-client/issues/2934

Changed the cards

2024-03-28 11:22 UTC, bastianjoel requested changes

2024-03-28 11:22 UTC, bastianjoel commented on client/src/styles.scss
Do not change this yet.

2024-03-28 11:27 UTC, bastianjoel requested changes

2024-03-28 11:27 UTC, bastianjoel commented on client/src/app/ui/modules/import-list/components/via-backend-import-list/backend-import-list.component.html
> +        <span id="code" class="foreground-warn" *ngFor="let entry of possibleFields; let last = last">
This will result in invalid html. https://www.w3schools.com/html/html_id.asp

2024-03-28 12:45 UTC, bastianjoel requested changes

2024-03-28 12:45 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/home/pages/start/components/start/start.component.html
> -        <div class="app-content underlined-links">
If you remove `app-content` you need to adjust the page object for the home page in `client/tests/integration/page-objects/meeting/home/detail.ts`. 
I would suggest adding something like `id="meeting-info-content` to the element and adjust the page object then.

2024-03-28 13:19 UTC, bastianjoel approved these changes

2024-04-02 08:49 UTC, Elblinator commented
I got a long change request via mail
I'll work through it

2024-04-03 13:03 UTC, Elblinator commented
verbal approve from @MSoeb

2024-04-05 07:47 UTC, bastianjoel requested changes

2024-04-05 07:47 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/components/participant-detail-view/participant-detail-view.component.html
> +                <mat-form-field class="form45 force-min-with" *ngIf="showVoteWeight">
This needs to be reverted as the layout was changed in #3497

2024-04-05 08:06 UTC, bastianjoel approved these changes

2024-04-05 08:13 UTC, merged