Fix visibility of participant list singleitem menu
OpenSlides/openslides-client pull request #3541
Opened 2024-04-11 09:37 UTC by reiterl

Resolve #3486

2024-04-15 10:18 UTC, Elblinator requested changes
A participant with the new Permission can update participants sees too little information in the three dot menu 
What additionally should be visible: 
- edit details
- swap mandates
- send invitation email

2024-04-15 12:01 UTC, reiterl commented
This issue is not about, what is seen in the `singleItemMenu`, but about, if the
3 dots icons are shown or not. If the menu is empty, the 3-dots should not be shown.

@Elblinator  please retest, and for the other stuff open a new issue.

2024-04-15 13:31 UTC, Elblinator commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
> +        return this.operator.hasPerms(Permission.userCanManage) || this.canChangePassword(user);
please change to ```this.operator.hasPerms(Permission.userCanUpdate)```

2024-04-15 13:32 UTC, Elblinator requested changes
Please change the permission

I'll create a new Issue for my previous CR

2024-04-16 09:45 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts
> +        return this.operator.hasPerms(Permission.userCanManage) || this.canChangePassword(user);
done

2024-04-16 09:46 UTC, reiterl commented
okay, I  have changed the permission check in canSeeSingleItemMenu.

2024-04-16 10:50 UTC, bastianjoel approved these changes

2024-04-18 06:03 UTC, Elblinator approved these changes

2024-04-18 06:03 UTC, merged