In pdf export of attachment trim trailing '/' of url setting
OpenSlides/openslides-client pull request #3551
Opened 2024-04-12 08:05 UTC by reiterl

Resolve #3539

2024-04-15 10:32 UTC, Elblinator approved these changes

2024-04-16 07:15 UTC, jsangmeister commented
This is not a clean solution, URLs should never be simply concatenated, but joined by a dedicated functions. This removes the possibility of these kinds of errors. Therefore, the string concatentation in lines 769f.:
https://github.com/OpenSlides/openslides-client/blob/204a66dcf2cc7819a0783e6d897cc5433faaec91/client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts#L769-L770

should be replaced by a suitable URL join method instead of trimming the instance URL manually.

2024-04-24 09:46 UTC, reiterl commented
@jsangmeister Please give an example solution for this. I discussed this issue 0.75 h with another frontend developer. We didn't come to a solution. (URL doesn't work here).

2024-04-24 09:51 UTC, jsangmeister commented
Why does `URL` not work? From a quick search, https://developer.mozilla.org/en-US/docs/Web/API/URL/URL seems to do what we want.

2024-04-24 10:01 UTC, reiterl commented
The base with subpathes doesn't work like expected
```
e.g. url = "https://example.com/test/"
path = "/system/get/4"
new URL(url,  path).toString() -> "https://example.com/system/get/4"
```

2024-04-24 10:11 UTC, bastianjoel commented
> The base with subpathes doesn't work like expected
> 
> ```
> e.g. url = "https://example.com/test/"
> path = "/system/get/4"
> new URL(path, url).toString() -> "https://example.com/system/get/4"
> ```

It should work if you remove the first slash from the path. But I second that using `URL` is not really necessary here. As said in my previous comment you might just use another way to get the instance url so you do not need to rely on user input.

2024-04-24 10:25 UTC, jsangmeister commented
`Location.joinWithSlash` seems to be a solution (https://angular.io/api/common/Location#static-properties)

2024-04-24 10:30 UTC, reiterl commented
I will check the Location.joinWithSlash Solution.

2024-04-24 11:22 UTC, reiterl commented
The Location joinWithSlash solution seems to work fine. I also checked url with subpaths. 

Please review again.

2024-04-24 11:26 UTC, jsangmeister requested changes

2024-04-24 11:26 UTC, jsangmeister commented on client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
> +                            link: Location.joinWithSlash(instancUrl, fileUrl),
```suggestion
                const link = Location.joinWithSlash(instanceUrl, fileUrl);
                attachments.push({
                    ul: [
                        {
                            text: attachment.getTitle() + `: ` + link,
                            link: link,
```
While you're at it, please fix the variable name typo (`instancUrl` -> `instanceUrl`)

2024-04-24 12:17 UTC, bastianjoel requested changes
I still don't like this usage of `this.organizationSettingsService.instant('url')`.

2024-04-25 06:50 UTC, reiterl commented
@bastianjoel  I didn't change the way how to get the organization setting here. What don't you like about it this way?

2024-04-25 07:14 UTC, jsangmeister approved these changes

2024-04-26 07:10 UTC, bastianjoel approved these changes
Because you could just use the current url and with that prevent dealing with issues coming from a url that can be set by user input. 

Anyway I see that this might be helpful to for example create documents from staging instances.

2024-04-26 09:11 UTC, reiterl commented
@Elblinator Please check, if this is still okay, after the improvements to the code.

2024-04-26 11:22 UTC, Elblinator approved these changes
seems to work

2024-04-26 11:23 UTC, merged