FIX Navigation Between Motions and Amendments
OpenSlides/openslides-client pull request #3559
Opened 2024-04-16 07:03 UTC by reicda

2024-04-16 14:37 UTC, bastianjoel requested changes

2024-04-16 14:37 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
> +            this.substituteSurroundingMotions(indexOfCurrent, true);
I guess it would be better to just set the correct value instead of correcting it afterwards.

2024-04-16 14:37 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
> +                while (index < this._sortedMotions.length - 1) {
I'd prefer a for loop here. When changing this to return the next suitable motion it should also be possible to reduce this into one loop.

2024-04-17 09:21 UTC, bastianjoel approved these changes
Looks good! Just one minor remark.

2024-04-17 09:21 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts
> +     */
Doc needs to be updated or removed. For private methods it is normally okay to not add a docblock.

2024-04-18 07:09 UTC, Elblinator requested changes
If a motion is created then the arrow navigation is from the amendment-list is shown.

Please make sure that the correct navigation is shown after creating a motion/amendment:
- A) If a motion is created then the arrows/navigation from the motion-list should be shown  
- B) if an amendment is created and amendments are shown together with motions the arrows from the motion-list should be shown 
- C) if an amendment is created and amendments are NOT shown together with motions then the arrows from the amendment-list should be shown (this already happens but could change if A and B are implemented)

2024-04-29 12:39 UTC, Elblinator approved these changes

2024-04-29 12:40 UTC, merged