Hide empty space if three dot menu is not shown
OpenSlides/openslides-client pull request #3590
Opened 2024-04-19 10:44 UTC by Elblinator

closes #3587 

I removed the check for the ownPage (and set it to false always) to hide the option to change own password at all at this specific place.
The previous behaviour seemed unintuitive. (Only account/organization admins got the option to change their own password at this place. these admins were not allowed to update participants in the meeting in question) 
Note: Users are still able to change their own password via the my profile dialog

2024-04-23 13:30 UTC, rrenkert approved these changes

2024-05-15 08:26 UTC, bastianjoel requested changes
I would prefer a cleaner solution for this. 

For example it should not be too hard to extend `scrolling-table-cell.directive.ts` to accept observables.

2024-05-21 08:42 UTC, bastianjoel requested changes

2024-05-21 08:42 UTC, bastianjoel commented on client/src/app/ui/modules/scrolling-table/directives/scrolling-table-cell.directive.ts
> +            });
I don't see this getting closed anywhere.

2024-05-21 14:06 UTC, bastianjoel requested changes
No

2024-05-21 15:09 UTC, bastianjoel approved these changes

2024-05-21 15:09 UTC, bastianjoel approved these changes

2024-05-22 11:52 UTC, rrenkert approved these changes

2024-05-22 11:52 UTC, merged