Add spokesperson to motion xlsx export
OpenSlides/openslides-client pull request #3592
Opened 2024-04-19 11:13 UTC by bastianjoel

2024-04-19 13:06 UTC, luisa-beerboom approved these changes

2024-04-22 06:16 UTC, Elblinator requested changes
If previously activated and exported then the spokesperson is exported even if the setting-option is currently deactivated

Repro:
- activate spokesperson 
- select a spokesperson in a motion
- export motions with spokesperson
- deactivate option in settings
- export motions again
- spokesperson is still in the file

2024-05-06 07:22 UTC, Elblinator commented
ping

2024-05-22 12:47 UTC, bastianjoel commented
pong

2024-05-23 09:15 UTC, Elblinator approved these changes

2024-05-23 09:15 UTC, merged