Remove history mode
OpenSlides/openslides-client pull request #3676
Opened 2024-05-15 13:02 UTC by bastianjoel

resolves #3657

2024-05-15 13:54 UTC, luisa-beerboom approved these changes

2024-05-16 09:04 UTC, Elblinator requested changes

2024-05-16 09:04 UTC, Elblinator commented on client/src/app/site/pages/meetings/pages/history/components/history-list/history-list.component.html
>                  [ngClass]="{ 'links-disabled': !isSuperadmin }"
```suggestion
               class="links-disabled"
```

2024-05-16 09:04 UTC, Elblinator commented on client/src/app/site/modules/site-wrapper/services/voting-banner.service.ts
>          // display no banner if in history mode or there are no polls to vote
please remove history mode from comment

2024-05-23 09:08 UTC, Elblinator approved these changes

2024-05-23 09:09 UTC, merged