Fix new styling
OpenSlides/openslides-client pull request #3700
Opened 2024-05-24 12:47 UTC by Elblinator

closes #3699 
The motion-detail view is fixed with this change. I do not know where else this was affected, please test accordingly

2024-05-27 07:26 UTC, luisa-beerboom approved these changes

2024-05-29 09:33 UTC, MSoeb approved these changes
Looks fine. 

Further information what is also affected:
- election detail view
- workflow detail view
- category detail view
- participant group permission overview
- user detail view

2024-05-29 09:55 UTC, MSoeb requested changes
Found a small issue. Have to revert my approval. The color status boxes, for example in the workflow or in the category, have changed their position slightly. The boxes are not aligned in the center. 

Example: Box 'angenommen' is not centered. 
![image](https://github.com/OpenSlides/openslides-client/assets/105491030/62d63233-4a86-426f-8c07-a88912e9e059)

2024-05-29 11:24 UTC, Elblinator commented
This is not a new bug, please create a new issue for this

2024-05-29 14:29 UTC, Elblinator commented
This Issue was already in main 
I create it's own Issue for that:
https://github.com/OpenSlides/openslides-client/issues/3710

2024-05-30 14:32 UTC, emanuelschuetze approved these changes

2024-05-30 14:36 UTC, MSoeb approved these changes
Works fine.

2024-05-30 14:37 UTC, merged