Mdc migration chip, button, menu, table, checkbox and list
OpenSlides/openslides-client pull request #3706
Opened 2024-05-28 10:34 UTC by bastianjoel

resolves #2934
closes #3694
closes #3696 
closes #3703

2024-05-29 14:27 UTC, bastianjoel commented
We should maybe replace the chips with an custom component. 
@Elblinator maybe you could have a look on that?

2024-06-05 13:31 UTC, bastianjoel commented
@MSoeb Did you already discuss with @Elblinator that the change request in https://github.com/OpenSlides/openslides-client/pull/3694 and came to the conclusion that we will not be fix them?

2024-06-07 13:01 UTC, Elblinator requested changes
Please merge into main, a PR is missing which makes the projection mainly not testable

Already found change requests:

- [x] Imports: if a file is selected then the file-name is lower than the button ‘select file’ and the clear button
![Screenshot_20240607_141602](https://github.com/OpenSlides/openslides-client/assets/69210919/1c9d0d05-5745-4cf4-bc7b-21d3d9d046c2)
- [x] committee-detail: mat-card-header from a meeting→the header is a bit too tall (it was height:40px plus padding-top:6px; now its ~48px plus padding-top:6
 probably bc of the wrong height: title too far up, “archived” and “public template” indicator too far down
![Screenshot_20240607_142804](https://github.com/OpenSlides/openslides-client/assets/69210919/da7fd103-e7cf-47f5-b000-be8d328d18bf)
- [ ] Account-create →the two buttons in the Initial password do not fit into the mat-form-field; please make them fit into one line again;
![Screenshot_20240607_143105](https://github.com/OpenSlides/openslides-client/assets/69210919/e37d42cf-f0d3-448c-b3cf-4fe24ba970c2)
- [x] Design edit/create dialogue → the colour field are now too big , please make them fit in a line again (max per line = 3)
- [x] right corner > my profile > change password: Error in console and not input fields: ERROR Error: NG0300: Multiple components match node with tagname button: MatButton and MatIconButton. Find more at https://angular.io/errors/NG0300
    at throwMultipleComponentError (core.mjs:11607:11)
- [ ] LoS- detail-view > three dot menu: the icons and the text are not aligned, please align them
![Screenshot_20240607_143456](https://github.com/OpenSlides/openslides-client/assets/69210919/706b8b58-0f8a-4636-a46b-797a0db1b439)
- [ ] projector-detail > current LoS: projector buttons have an ugly shadow
- [ ] meeting settings > setting detail: distance between items is very big: please remove the class setting-form-group 
- [ ] Motion-detail-view: The icons for a projected motion and the star-icon are differently aligned:
![Screenshot_20240607_142916](https://github.com/OpenSlides/openslides-client/assets/69210919/a3b5c8f9-5653-4b46-87b7-c541428f3641)
- [x]  in Chromium: [not always reproducable] if you open a dialog then a scrollbar appears
- [ ] [not always reproducable] Filter bar: if the option mat-divider and another checkbox is present then there is a unnecessary scrollbar-> This could be due to delayed loading. The scrollbar was there for the first few moments, but after a while it disappeared completely


Only notes for now: the following things need further discussion before they can be fixed:
they will be discussed after the change requests are implemented,
please do not fix them yet
- Nav-toolbar-content: on orga level and on meeting level look different, They should be unified. _Given that a lot of places are now in the darker theme: I would suggest turning the toolbar on the meeting-level darker_
- Group-Matrix give permissions more space the mat-cell is ~15px smaller and there is now padding-right:16px. Can the width be again 15 px bigger. I am unsure whether or not the paddig should stay there or not

2024-06-12 09:35 UTC, bastianjoel commented
> in Chromium: [not always reproducable] if you open a dialog then a scrollbar appears

While this might be related to another MDC migration this is not related to this PR. Please open another issue.

2024-06-12 10:35 UTC, bastianjoel commented
> [not always reproducable] Filter bar: if the option mat-divider and another checkbox is present then there is a unnecessary scrollbar-> This could be due to delayed loading. The scrollbar was there for the first few moments, but after a while it disappeared completely

As discussed

2024-06-13 12:00 UTC, Elblinator approved these changes
several places changed the appearance, but this was expected
In my opinion the appearance is okay as it is. 
But please @MSoeb also test it and give your feedback
We can of course also test together to get a better picture

2024-06-18 09:16 UTC, Elblinator requested changes
committee-detail if the meeting can forward or can be forwarded to by several other meetings:
the "More"/"Less" and the icon expand_more/expand_less is not aligned anymore

2024-06-18 14:58 UTC, Elblinator requested changes
A not complete list (testing everything will take a moment longer)
Please change the following things back to how they were before or state if it's the new default or hard to change back/why it's hard

- [x] In dashboard, the icon "layers" with the tooltip "Show committee" is not blue, please return it to the old colour
- [x] in every three-dot menu: 
    - [x] the text changed from font-size:14 to font-size : 16
    - [x] the icon changed from color: rgba(0, 0, 0, 0.54) to rgba(0, 0, 0, 0.87)
- [x] in  every list view the sort and filter button (icon and text) changed from color: rgba(0, 0, 0, 0.87) to color: rgba(0, 0, 0)
- [x] in the sort thing. The arrow (icon "arrow_downward"/"arrow_upward") changed the color from rgba(0, 0, 0, 0.54) to rgba(0, 0, 0, 0.87)
- [x] In the Filter-list mat-panel-title 
   - [x] font-size from 15px to 14px
   - [x] font-weight: from 400 to 500
- [x] as far as we could see every text (input/label) in a mat-form field changed it's font-size from 15px to 16px
- [ ] buttons:
   - [x] letter spacing changed from normal to 1.25
   - [ ] the color change from white to black (vise versa dependent on the dark/light mode)
   - [ ] mat-checkbox (e.g. in account edit view) the little check seems to be less central  
   - [ ] with mat-icon: changed size from 40 x40 to 48x48
- [ ] orga-level: tags font-weight of 500 is gone
- [ ] os-file-list home icon got smaller, (font-size changed from 24 to 18)
- [ ] in a dialog > mat-dialog-content > form > p:
   - [ ] font-size: 15px to 16px
   - [x] letter-spacing: normal to 0.5px 
 - [ ] mat-panel-title: 
    - [ ]  font-size: 15px to 14px
    - [ ] font-weight: 400 to 500
 - [ ] mat-list-item: letter-spacing from normal to 0,5

2024-07-05 13:20 UTC, bastianjoel commented
@MSoeb @Elblinator I am now finished working through our internal list with change requests. 

Everything marked there as wontfix are points which would require additional effort to implement or come with drawbacks in maintainability. If any of those points are mandatory we should discuss them.

2024-07-09 11:24 UTC, Elblinator reviewed
- [ ] In History: The refresh button is too big if the language is changed to German

- [ ] Checkboxes have different inside colours: 

- some change colour together with light and dark-mode (e.g. top-right-corner your own present box)
- some stay white in the middle
places I found these checkboxes:  meetings> settings, projector-list > edit projector dialog, participant-list, participant-detail-edit-view, structure-level create dialog, election-create-view, motion-detail.... 
If needed I can try to create the  full list, but for now I'll stop at this point of the list

2024-07-10 07:04 UTC, bastianjoel commented
> Checkboxes have different inside colours

I did this on purpose because I thought the contrast is quite bad and did not notice that it was black previously. The presence button uses a transparent icon and I cannot change it easily there. Should I change it back to black or is it okay as it is not?

2024-07-11 08:24 UTC, Elblinator approved these changes

2024-07-11 11:03 UTC, merged

2024-07-11 11:09 UTC, reiterl reviewed
I am not sure, if it is an issue, but I found some location in the source code, where:
class, ngClass and [class] is mixed. Else look good.

2024-07-11 11:09 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
> +                    </span>
class ngClass mix

2024-07-11 11:09 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.html
> +                    <span class="button-size" [ngClass]="projector.scroll !== 0 ? 'warn' : ''">
same.

2024-07-11 11:35 UTC, bastianjoel commented on client/src/app/site/modules/chip-select/components/chip-select/chip-select.component.html
> +            [class]="chipClass || 'grey'"
This is valid