Change fallback appearence, icon, no banner
OpenSlides/openslides-client pull request #3770
Opened 2024-06-11 17:20 UTC by reiterl

Resolve #3740

Please test with activated longpolling. I have no idea how to trigger this in my dev setup.

2024-06-12 08:34 UTC, bastianjoel approved these changes

2024-06-13 06:43 UTC, Elblinator requested changes
This is how it currently looks: 
![Screenshot_20240613_084011](https://github.com/OpenSlides/openslides-client/assets/69210919/07089b44-3bc0-4c15-8b05-0a116120342c)

To mimic the fallback mode:
in autoupdate-stream-pool.ts -> set singleWin to true 

Change request: 
Adjust the appearance of the icon to the appearance in the mock-up

2024-06-17 08:44 UTC, reiterl commented
I changed the icon and the style for it.

2024-06-19 11:25 UTC, Elblinator requested changes

2024-06-20 10:27 UTC, reiterl commented on client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.scss
> +    background: orange;
done.

2024-06-20 10:28 UTC, reiterl commented on client/src/app/site/modules/global-headbar/components/global-headbar/global-headbar.component.scss
> +    margin-top: -2px;
transform geadded. But not the -3 because with transform looks the -2 better.

2024-06-25 11:28 UTC, Elblinator reviewed
I would still recommend -3 px because it is more central (as far as I can see)
@Msoeb can you please say what you prefer?

With margin-top -2px:
![Screenshot_20240625_132306](https://github.com/OpenSlides/openslides-client/assets/69210919/05460863-5fe6-4cd7-adec-83b7277b9c88)

With margin-top -3px:
![Screenshot_20240625_132614](https://github.com/OpenSlides/openslides-client/assets/69210919/90b799d0-ad5c-4fc4-9410-efe21f8a85af)

2024-06-25 12:19 UTC, reiterl commented
Okay, I changed the margin top to -3px.

2024-06-25 14:14 UTC, Elblinator approved these changes

2024-06-25 14:14 UTC, merged