Fix poll display on delegation settings change
OpenSlides/openslides-client pull request #3790
Opened 2024-06-25 15:47 UTC by bastianjoel

resolves #3685

2024-06-27 14:57 UTC, Elblinator requested changes
The polls are still not loaded correctly => no change in behaviour

having any poll in the autopilot (e.g. a running poll) results in several Errors being thrown  in the console
```
base-repository.ts:396 ERROR 
TypeError: Cannot read properties of undefined (reading 'length')
    at AssignmentPollVoteComponent_ng_template_1_ng_container_1_ng_container_1_div_3_div_2_b_2_Template (base-poll-vote.component.html:67:29)
    at executeTemplate (core.mjs:11966:13)
    at refreshView (core.mjs:13461:13)
    at detectChangesInView (core.mjs:13626:9)
    at detectChangesInEmbeddedViews (core.mjs:13569:13)
    at refreshView (core.mjs:13485:9)
    at detectChangesInView (core.mjs:13626:9)
    at detectChangesInEmbeddedViews (core.mjs:13569:13)
    at refreshView (core.mjs:13485:9)
```
or a different example
```
auth-check.service.ts:93 ERROR 
TypeError: Cannot read properties of undefined (reading 'includes')
    at MotionPollVoteComponent.defineVoteOptions (base-poll-vote.component.ts:499:42)
    at MotionPollVoteComponent.updatePoll (base-poll-vote.component.ts:438:14)
    at set poll (base-poll-vote.component.ts:46:14)
    at writeToDirectiveInput (core.mjs:12852:34)
    at setInputsForProperty (core.mjs:13086:9)
    at elementPropertyInternal (core.mjs:12377:9)
    at Module.ɵɵproperty (core.mjs:16218:9)
    at PollCollectionComponent_ng_template_2_div_8_os_motion_poll_vote_1_Template (poll-collection.component.html:31:38)
    at executeTemplate (core.mjs:11966:13)
```

2024-06-28 09:03 UTC, Elblinator commented
The Error message seems to be not related to this issue. I just got the same Error while checking out main
I'll investigate the Error further and create new Issues

2024-07-03 06:36 UTC, bastianjoel commented
> The Error message seems to be not related to this issue. I just got the same Error while checking out main I'll investigate the Error further and create new Issues

Could you approve in that case?

2024-07-03 07:00 UTC, Elblinator approved these changes

2024-07-03 07:01 UTC, merged