Fix poll progress number
OpenSlides/openslides-client pull request #4025
Opened 2024-08-15 07:22 UTC by Elblinator

closes #3890

2024-08-15 13:52 UTC, bastianjoel requested changes
I would prefer a view model only solution. I am not exactly sure if you can access settings there directly. If not just set the method in the repository as done with `getFullName` for example.

2024-08-16 07:43 UTC, MSoeb approved these changes
Looks good

2024-08-21 11:46 UTC, MSoeb approved these changes
Looks good

2024-08-21 11:59 UTC, bastianjoel approved these changes

2024-08-21 11:59 UTC, merged