Prevent null in calculated group_ids of assign meetings
OpenSlides/openslides-client pull request #4124
Opened 2024-09-16 11:01 UTC by reiterl

Resolve #4085 

I don't understand, why the meeting.default_group_id is null in some rare cases, but it leads to an error, because it
sends null in group_ids. So I exclude broken stuff from this array.

2024-09-17 08:03 UTC, Elblinator approved these changes

2024-09-18 09:45 UTC, bastianjoel requested changes

2024-09-18 09:45 UTC, bastianjoel commented on client/src/app/site/pages/organization/pages/accounts/services/common/account-controller.service.ts
> +                    ).filter(id => !!id)
If there is a reason to always add the default group (which I guess there is) this looks like a very bad approach to "fix" this.

2024-09-18 10:07 UTC, reiterl commented
This pr doesn't solve the underlying problem. So I close it here.

2024-09-18 10:07 UTC, closed without merging