Change poll title in Autopilot
OpenSlides/openslides-client pull request #4139
Opened 2024-09-17 12:14 UTC by vkrasnovyd

Resolves #3828 

- Made 'getPollVoteTitle' return the default value for the motion poll (just the poll title without any extra info)
- Changed projected value for topic and election polls: removed brackets and their content, changed separator from " - " to ": "

2024-09-18 07:53 UTC, bastianjoel requested changes

2024-09-18 07:53 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/autopilot/components/poll-collection/poll-collection.component.ts
> +            [`Topic`, `Election`].includes(model)
The verbose names should not be used for checks. You could instead use `contentObject.COLLECTION` and then check against `Topic.COLLECTION` and `Assignment.COLLECTION`.

2024-09-18 08:55 UTC, bastianjoel approved these changes

2024-09-19 07:12 UTC, Elblinator approved these changes

2024-09-19 07:12 UTC, merged