Display origin motions in motion
OpenSlides/openslides-client pull request #4144
Opened 2024-09-17 13:13 UTC by bastianjoel

2024-09-23 09:00 UTC, bastianjoel commented
Talked with @emanuelschuetze that for origin the diff mode is sufficient and a selection is not necessary.

2024-09-23 09:01 UTC, bastianjoel commented
Line numbering is now using the default line numbering mode from origin meeting.

2024-09-23 09:04 UTC, bastianjoel commented
> The user of the forwarded motion is wrong

@rrenkert This is not part of #3529

2025-01-27 16:27 UTC, emanuelschuetze submitted a review, later dismissed
I found some issues:
- [ ] create main in memotion incl. 2 amendments and 1 change reco -> forward (original) motion -> open forwarded motion in target meeting: NO amendments visible, only change reco!

Now activate origin-motion-mode in motion detail of target meeting and show original motion:
- [ ] ~~change recommendation is missing! (only amendments visible)~~
- [ ] autoupdate does not work (changes in original motion needs reload in target meeting) (wontfix)
- [ ] ~~select boxes for linenumbering and text version is missing~~ 
- [ ] ~~motion poll is linked to poll detail which cannot opened -> remove link (not required)~~
- [ ] ~~recommendation field is empty!~~
- [ ] ~~(login as delegate) linenumbers, amendmetns and change recos are missing!~~
- [ ] ~~(as delegate) show linked arrows to amendment only if user has access rights to original meeting~~

- [ ] whats happened if identifier already exists in target meeting? currently add "-1" suffix => better: " (1)", e.g. "A001-Ä001 (1)"

Problems with forwording:
- [ ] forward main motion incl. all amendments -> show in forward dialog HOW MANY amendments/change recos will be forwarded
- [ ] forward main motion incl. e.g. 2 amendments -> snack message shows "1 motion successfully forwarded" => missing indication that amendments (how many?) also forwared -> e.g. "1 motion and 2 amendments successfully forwarded"

Wishes / improvements:
- [ ] allow multiselect forwarding in motion list (that meens only the selected motions should be forwarded, e.g. without special/rejected amendment); note: forwareding via amendment list should not be possible because main motion is missing there.
- [ ] ~~place new icon in diff box of amendment if a change recommendation is available in this amendment (it must be clear wether a change reco exists in amendment)~~
- [ ] orange original motion view: use meta data in 2 column layout to make the view more beautiful
- [ ] new meeting settings: original motion view (tab) always enabled (default off)
- [ ] (later!) Lock 'View origin motion' permission - only up to certain level/meeting ("Sperrriegel") - definable in committee ("only up to here")

2025-01-29 12:30 UTC, bastianjoel commented
#4426 might needs to be fixed again here as the code changed too much to apply the original fix.

2025-02-03 11:15 UTC, bastianjoel commented
Line numbering mode will be used from the current meeting if origin meeting settings not available.

2025-02-03 14:37 UTC, bastianjoel commented
> keep origin toggle active when navigating

We need to further discuss what we are saving here. When just saving the origin meetings it could be that when revisiting a motion multiple origin motions are selected because it is possible to pass motions between meetings multiple times. Maybe it would be better to save the last selected level.

2025-02-03 14:38 UTC, bastianjoel commented
Currently change recommendation do not get sent by the autoupdate service for users who are not in the origin meeting. Also meeting names do not get sent because the restriction mode for meeting names changed.

2025-02-18 13:15 UTC, MSoeb requested changes
There are several problems which need to be solved:

----
Different changes to a motion which contains an amendment and in the amendment is a change reco are needed: 
- [x] currently two warning signs appear in motion view. -> wanted behavior: Only conflict should appear as warning. 
- [x] The change reco should get a new icon and should be replaced. The icon should be an Info icon which should have the the primary color and be inverted. The icon should be placed in the lower right corner of the amendment matcard.
- [ ] To avoid overlays with the three-dot-menu in an amendment, the three-dot-menu should be aligned higher and always centered to the first line of an amedment.

-----
- [x] Origin back view: If a user selects an origin view tab and scales the browser window, the tab snaps away from the selected tab -> Wanted: View should not change by scaling of window.
- [x] Origin view tab: Is it possible to display the metadata in two columns? The back view needs a lot of space in the current design.

View as participant which has NO permission to see origin motions:
- [x] Names of origin committees are not visible in the motion metadata -> Wanted: Names should appear

View as participant with the permission to see origin motions:
- [x] Committee names are also missing. It is possible hit the switch of the origin motions, but the orgin committee names are also not visible as tabs. > Wanted: Committee names should be visible.

-------
Below are a few points that were discussed in the previous step but not documented here. These are listed below for the sake of completeness:
- [x] Origin view: Line number and motion view selection layout clashed with long motion titles
- [x] If the origin view tab was opened once, the outlines of the matcard of the main motion and the origin view were not visible anymore
- [x] Origin view: If the origin view contained amendments, the matcars of them didn't scale correctly by changing the window size.

2025-02-19 10:33 UTC, bastianjoel commented
> Names of origin committees are not visible in the motion metadata -> Wanted: Names should appear
> Committee names are also missing. It is possible hit the switch of the origin motions, but the orgin committee names are also not visible as tabs. > Wanted: Committee names should be visible.

Before this PR there were only meeting names displayed. We keep this behavior. 
In case you mean that the meeting names are not displayed then you used an outdated autoupdate version.

2025-02-19 10:41 UTC, bastianjoel commented
> Origin view tab: Is it possible to display the metadata in two columns? The back view needs a lot of space in the current design.

I already talked about this with @emanuelschuetze. At the current stage we do not want to do this yet.

2025-02-26 08:37 UTC, MSoeb requested changes
- [ ] If a motion contains a forwarding, the target meeting link doesn't work. Clicking it results in a spinning wheel. Reload needed. Same happens with links to source meetings. - Tested it as superadmin. -> Wanted: Source/Target meeting links should work for accounts which have the permission to use them, without getting a spinning wheel. 
- [x] New Change Request Icon: Currently it has a view limitation. The user need to activate the checkmark for amendments. > Wanted: Should always be visible. 
- [x] Amendments: Information of Number, Status and submitter should alaways be visible.
- [x] Scaling of website - origin view: By scaling the website smaller, the orange outline get's lost. -> Wanted: Outline should always be visible after scaling.
- [x] Scaled motion with tabs: After scaling the tabs hover above the motion matcard. > Wanted: Tab positions should remain at matcard after scaling.
- [x] Origin view: The buttons for Line numbering and view option should be placed under the metadata. If a summary of changes is visible, they should be placed between metadata and summary of changes.
- [x] Origin view - unfold button: The unfold button should be placed on the left side and it should include the word  'Metadata'
- [x] Motion metadata - origin / forwarded meetings names: The names are still not visible for persons which doesn't have the permission to see access the meeting. > Wanted: The names should always be visible. If the user has the permission to access the meetings, links should be available. If not, the names should be visble, but without a link. Please take care: Also the names in tabs are not visible. / Additional hint: I've tested this with a user which has no access to the origin meeting.
- [x] Scenario - User opens origin view, but he hasn't the permission to open source meeting --> consequence: Change requests and amendments are not visible in origin view.
- [ ] Add new setting in motions > view: Activate origin view. / We need a setting to deactivate the new feature by default. Most meetings won't need it and therefor we should integrate an option to deactivate it by default.
- [ ]  Add new setting in motions > view: Add a new option to toggle defautl behavior of the slide controller. / Hint: More important is the other setting.
- [ ] Clsoed meetings: If a closed meeting is a source meeting of a motion, the slide controller should not available, no tab should be shown and the meeting name should have a small closed lock icon right to it.
- [ ] Origin view > summary of changes: Please delete the arrows (which are links ot the source meeting). They are not needed.

2025-02-28 12:46 UTC, MSoeb requested changes
Small batch of CR:

- [ ] Closed Meeting in metadata: Currently the word 'Closed' is readable. This should be changed to the lock-Icon
- [ ] New Change request Icon: It should also be available in the 'normal' motions, not only in the origin motions. (I think this worked before the last changes)

As discussed, the other open changes are also to be integrated.

2025-03-10 13:55 UTC, bastianjoel commented
> New Change request Icon: It should also be available in the 'normal' motions, not only in the origin motions. (I think this worked before the last changes)

It is only displayed when "Show all changes" is active.

2025-03-10 15:10 UTC, bastianjoel commented
> Clsoed meetings: If a closed meeting is a source meeting of a motion, the slide controller should not available, no tab should be shown and the meeting name should have a small closed lock icon right to it.

It is not possible to show the lock icon as we do not provide the info if a meeting is locked to users who are not allowed to see those meetings.

2025-03-10 15:38 UTC, bastianjoel commented
> Closed Meeting in metadata: Currently the word 'Closed' is readable. This should be changed to the lock-Icon

Cannot reproduce. Also it is not displayed if a meeting is closed.

2025-03-14 13:21 UTC, MSoeb requested changes
- [x] backtracking view (Tab): Behind identifier a colon is missing. Example: 'A01: Toller Antragstitel'
- [ ] Settings > Motions > setting 'Enable display of original forwarded motions': Setting doesn't work correctly. After deactivation, the slider is still visible. -> Target: When deactivated, the slider should no longer be visible. 
- [ ] Settings > Motions > setting 'Preload original motions': Please hide it deactivated in the client.

Slider Button in motions after forwarding
- [ ] Slider needs tool tip with text 'activate backtracking'

Furthermore I have created additional requirements which I put in another issue. If a change request is incorrectly placed in the PR or issue, please transfer it to the correct place.

Issue link: (https://github.com/OpenSlides/openslides-client/issues/4756)

2025-03-17 12:31 UTC, luisa-beerboom approved these changes

2025-03-17 14:25 UTC, MSoeb approved these changes

2025-03-17 14:25 UTC, merged