Add default poll method to motion settings
OpenSlides/openslides-client pull request #4173
Opened 2024-09-24 08:09 UTC by Elblinator

closes #4043

2024-09-24 10:20 UTC, bastianjoel approved these changes

2024-09-24 11:57 UTC, bastianjoel requested changes

2024-09-24 11:57 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/modules/motion-poll/index.ts
`index.ts` should not contain any definitions

2024-09-24 13:55 UTC, bastianjoel approved these changes

2024-09-27 13:14 UTC, MSoeb approved these changes

2024-09-27 13:14 UTC, merged