Fix Motion-list CSV export and add new Version to export
OpenSlides/openslides-client pull request #4177
Opened 2024-09-25 08:51 UTC by Elblinator

closes #4050 

Added the editorial final version for the CSV export 
=> the PDF now has the two options "final Version" and "editorial final Version", This can be changed back to only one option (If that is wanted which version should be used?)
=> The CSV only has two options ("Original" and "editorial final" Version), are these the only two options wanted for the CSV export?

2024-09-25 11:04 UTC, Elblinator commented
After talking with @emanuelschuetze:
- The editorial final version was reverted
- Two options are neough for CSV export

- we found a bug, where the crMode was not reset correctly after switching from pdf to csv

2024-09-26 11:55 UTC, bastianjoel requested changes

2024-09-26 11:55 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/components/motion-export-dialog/components/motion-export-dialog/motion-export-dialog.component.ts
> +    }
This is weird behavior. Just do the check on assignment. 

Return and assignment values of getter/setters should always be the same.

2024-09-26 13:09 UTC, bastianjoel approved these changes

2024-09-27 12:43 UTC, rrenkert approved these changes

2024-09-27 12:43 UTC, merged