Get meeting-mediafile url with url property in motion pdf export
OpenSlides/openslides-client pull request #4189
Opened 2024-09-30 07:26 UTC by reiterl

Resolve #4182

2024-09-30 12:29 UTC, bastianjoel requested changes

2024-10-01 08:18 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts
done

2024-10-01 11:08 UTC, bastianjoel approved these changes

2024-10-14 08:38 UTC, Elblinator approved these changes

2024-10-14 08:39 UTC, merged