Fix breadcrumb in global search
OpenSlides/openslides-client pull request #4222
Opened 2024-10-07 11:40 UTC by reiterl

Resolve #4197

Fixes problem with marks in breadcrumbs of the global search for meetings and committees.

2024-10-10 06:35 UTC, Elblinator approved these changes

2024-10-18 08:53 UTC, bastianjoel requested changes

2024-10-18 08:53 UTC, bastianjoel commented on client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
AFAIK these fields are not sanitized.

2024-10-28 13:11 UTC, reiterl commented on client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
So what do you think, should I do then?
Add a function `sanitizeHTML`  which includes the DomSanitizer and sanitize the two values with HTML Security Context?

2024-11-12 10:53 UTC, bastianjoel commented on client/src/app/site/modules/global-headbar/components/global-search/global-search.component.html
I think for now it would be sufficient to just remove the `<mark>` tags from the fields.

2024-11-12 12:52 UTC, reiterl commented
Remove the mark tags and no longer use inner html.
It needs a small review and test again.

2024-11-12 13:58 UTC, bastianjoel approved these changes

2024-11-13 08:04 UTC, Elblinator approved these changes

2024-11-13 08:04 UTC, merged