Prevent translation of repo filter options
OpenSlides/openslides-client pull request #4231
Opened 2024-10-08 14:39 UTC by bastianjoel

resolves #4209

2024-10-09 06:45 UTC, reiterl requested changes
filtermenu: okay, But if you select the filter, it is still translated.
So incomplete.

2024-10-09 07:27 UTC, Elblinator commented
After checking the PR out for me neither the groups nor the structure levels were translated anymore. Please provide a reproduction. 
For (testing) missing/too much translation I like to create a group/structure level with the name "Agenda" if the name is translated to "Tagesordnung" I know a string is marked as "to be translated"

2024-10-09 09:03 UTC, reiterl approved these changes
Yes, this seems to be the missing part.

2024-10-10 06:30 UTC, Elblinator approved these changes

2024-10-10 06:31 UTC, merged