Small fix to subscribeTo
OpenSlides/openslides-client pull request #4245
Opened 2024-10-10 11:17 UTC by reiterl

Resolve #4240 

The `subscription.unusedSubscriptions` here can be undefined, now the code can handle it.

2024-10-11 10:06 UTC, bastianjoel requested changes
The error happens because there is a meeting specific subscription is missing a unused subscription. Please fix this instead of just suppressing the error message. 

Also please log a warning to the console if `subscription.unusedSubscription` is undefined at that place.

2024-10-11 10:12 UTC, bastianjoel commented
Also PLEASE improve you PR naming. The title does not provide any helpful information. Something like "Fix subscribeTo handle undefined `unusedSubscription`"

2024-10-11 11:26 UTC, reiterl commented
@bastianjoel What is this unusedSubscriptions for? In the interface the field is optional.

2024-10-18 08:28 UTC, bastianjoel approved these changes

2024-10-18 08:28 UTC, bastianjoel commented on client/src/app/site/services/model-request.service.ts
> +            } else if (subscription.unusedSubscription?.closed) {
```suggestion
            } else if (subscription.unusedSubscription.closed) {
```

2024-10-18 09:16 UTC, Elblinator approved these changes

2024-10-18 09:25 UTC, merged