Add word-break style to keep width in account-detail view
OpenSlides/openslides-client pull request #4270
Opened 2024-10-16 08:11 UTC by reiterl

Resolve #3990

2024-10-18 08:56 UTC, bastianjoel approved these changes

2024-10-18 09:47 UTC, Elblinator requested changes

2024-10-18 09:47 UTC, Elblinator commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.scss
> +        word-break: break-all;
```suggestion
        word-break: break-word;
```

2024-10-28 07:24 UTC, reiterl commented on client/src/app/site/pages/organization/pages/accounts/pages/account-detail/components/account-detail/account-detail.component.scss
> +        word-break: break-all;
done.

2024-10-28 07:36 UTC, merged