Create two new participant filters
OpenSlides/openslides-client pull request #4307
Opened 2024-10-30 09:31 UTC by luisa-beerboom

See #4154 

Also ensured the poll progress bar would consider the delegation settings => Please test.

@MSoeb I didn't really put much thought into the phrasing in the interface. @Elblinator I know I put you as a code reviewer, but if there is necessary changes in terms of phrasing, could you perhaps make those, idk what would be most understandable to the users.

2024-10-30 11:08 UTC, Elblinator approved these changes
Code review

2024-11-01 09:42 UTC, bspekker requested changes
1. When filter "Can vote for groups" is set, "For groups: total votes" should not count person that is delegated to vote but not in the eligible voting group. (Delegated vote to person in a non-vote-eligible group is currently counted double.)
2. New filters should disappear when setting "activate vote delegations" is not toggled in settings
3. Strings need changing, is still in discussion.

2024-11-04 11:50 UTC, bspekker submitted a review, later dismissed
As discussed, delete countable vote filter.

Adjust wording:
  - "Can vote for groups" to: "Voting rights" (German "Stimmrechte")
  - "(Vote weight 8; For groups: Total votes 5, Vote weight 11)" to: "(Voting rights 5, Vote weight 11) (delete first vote weight) (German: (Stimmrechte 5, Stimmgewichte 11) )

2024-11-06 15:44 UTC, MSoeb approved these changes

2024-11-07 07:25 UTC, merged