Fix list election mobile layout
OpenSlides/openslides-client pull request #4385
Opened 2024-11-22 14:19 UTC by anbebe

Closes #4358

2024-11-25 09:52 UTC, Elblinator commented on client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
> +                                        poll.options[0].isListOption,
- please remove isSplitSingleOption 
- change poll.options... to poll.isListPoll
- Add !isMobile to yna-grid

2024-11-25 09:52 UTC, Elblinator commented on client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
> +                                        @if (poll.options[0].isListOption) {
poll.isListPoll

2024-11-25 10:00 UTC, Elblinator commented on client/src/app/site/pages/meetings/modules/poll/components/base-poll-vote/base-poll-vote.component.html
> +                                    @if (poll.options[0].content_object) {
- poll.isListPoll
- and poll.options[0]?.content_object

2024-11-25 12:18 UTC, Elblinator requested changes

2024-11-25 12:18 UTC, Elblinator commented on client/src/app/site/pages/meetings/pages/polls/view-models/view-option.ts
> +
Please remove unused code

2024-12-02 14:15 UTC, Elblinator approved these changes
code review

2024-12-03 16:18 UTC, bspekker requested changes
Layout for voting method YNA per list looks good. 

New error for voting method YNA per candidate in the mobile layout: 
![image](https://github.com/user-attachments/assets/8902be0c-08c9-4dfd-913a-9bb30b3eaff9)
The YNA options are not above the buttons for the options. 
The caption of the buttons should always be directly above them.

2024-12-05 12:39 UTC, Elblinator approved these changes
code

2024-12-05 13:26 UTC, bspekker approved these changes

2024-12-05 13:27 UTC, merged