Rm strange, broken distinctUntilChanged timestamp logic
OpenSlides/openslides-client pull request #4412
Opened 2024-11-27 10:37 UTC by reiterl

Resolve #4303 

Remove a strange distinct until changed timestamp logic which leads to failures in the issue.
I don't know, what the reason for this logic is, I think performance problems. So a whole test of the motion detail component is needed.

2024-11-27 11:56 UTC, luisa-beerboom reviewed
The `motion-change-recommendation-controller.service.ts`  there is a method `getChangeRecosOfMotionObservable` that has the exact same code. If this code is broken, that one should be as well. Please check that.
If the change recommendation code is also broken, the entire `viewModelUpdateTimestamp` logic can be removed. If not, Maybe reconsider whether this `distinctUntilChanged` is actually at fault

2024-11-28 09:09 UTC, reiterl commented
I worked on fixing the update-timestamp at update, used the changedModels method for it. Test works.

2024-11-28 09:10 UTC, reiterl commented
@luisa-beerboom  Please look at the my new solution.

2024-11-28 10:05 UTC, luisa-beerboom approved these changes
You should probably change the title of this PR

2024-12-02 15:39 UTC, Elblinator requested changes
This still doen't fix the Issue:
I created a motion with 8 paragraphs 
and added 5 amendments (in paragraph 1,2,3,7 and 8)

- Changing the first state sometimes works
- Sometimes it updates after three amendment's states were changed
- sometimes it updates if I reset all changes amendments to submitted

step to step reproduction:
1. create motion with 200 words and 8 paragraphs (blindtextgenerator)
2. Create 5 amendments (in line 1-2, 3-4, 5, 13-14 and 15), I deleted the first word for each amendment
3. updating to the state to "accepted" or "not decided" (of any amendment) updates immediately, updating to "not decided" does not change the view automatically 

(I called stop-dev and run-dev, the workflows are the default dev ones

2024-12-03 12:44 UTC, reiterl commented
@Elblinator showed me the problem on his computer. I build a small change, comparing the state_ids in the distinctUntil part.

2024-12-04 10:20 UTC, bspekker approved these changes
functionality tested

2024-12-04 10:25 UTC, merged

2024-12-09 08:54 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/services/common/amendment-controller.service/amendment-controller.service.ts
> +                    prev?.map(e => e.state_id).equals(curr?.map(e => e.state_id))
Also this should be done in `motion-change-recommendation-controller.service.ts` too.