Add svg files as header option in pdf export
OpenSlides/openslides-client pull request #4443
Opened 2024-12-03 08:58 UTC by anbebe

Closes #3586

2024-12-09 10:29 UTC, bastianjoel requested changes

2025-01-08 13:13 UTC, Elblinator approved these changes
function

2025-01-10 12:46 UTC, bastianjoel requested changes

2025-01-10 12:46 UTC, bastianjoel commented on client/src/app/gateways/export/pdf-document.service/pdf-document.service.ts
> +                        const text = await fetchResult.text();
You are downloading the image twice.

2025-01-11 15:00 UTC, bastianjoel approved these changes

2025-01-14 14:31 UTC, Elblinator requested changes
Now the logo is not exported anymore

2025-01-16 12:05 UTC, Elblinator approved these changes
Functionality

Please fix conflicts

2025-01-17 07:58 UTC, merged