Update Meeting Info: change count structure levels
OpenSlides/openslides-client pull request #4450
Opened 2024-12-04 10:01 UTC by reiterl

Resolve #4271 

In non-parliament mode add the time to all structure levels of a speaker user.

2024-12-05 14:10 UTC, reiterl commented
Add a dummy structure level in parliament mode, too.

2024-12-09 10:52 UTC, bastianjoel requested changes

2024-12-09 10:52 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
> +        const map_for_aggregation = new Map<Id, SpeakingTimeStructureLevelObject>();
```suggestion
        const mapForAggregation = new Map<Id, SpeakingTimeStructureLevelObject>();
```

2024-12-09 10:52 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/home/pages/meeting-info/components/meeting-info/meeting-info.component.ts
> +                                            fieldset: FULL_FIELDSET
Why do you need everything here? This can be extremely much.

2024-12-09 11:52 UTC, reiterl commented on client/src/app/site/pages/meetings/pages/agenda/modules/list-of-speakers/services/list-of-speakers-controller.service.ts
> +        const map_for_aggregation = new Map<Id, SpeakingTimeStructureLevelObject>();
done

2024-12-09 12:09 UTC, reiterl commented
I tried to fix the problems, but run into a speaker.user is no set error in non-parliament mode, I need to debug that.

2024-12-12 11:43 UTC, Elblinator requested changes
Only non-parlamentarian modus: 
1. If the structure level are not preloaded somewhere else the table shows "no data" 
(Repo: let someone speak, navigate to "Count completed requests to speak" > you see data, reload page > "no data" is shown)
2. please show the users who have no structure level in the table (same appearance as in the parlamentarian-modus but only people with no structure level at all are counted

Styling: 
in parlamentarian-modus and non-parlamentarian-modus make "Without Structure Level" the font-style: italic; 

Sorting: 
Please sort the structure level alphabetically 
With the exception of "Without Structure Level" please put that item at the end of the list

2024-12-16 09:50 UTC, reiterl commented
I don't like this issue anymore. Deassigned.

2024-12-16 10:45 UTC, reiterl commented
I have written a fix for the subscription problem and non-structure level case for non-parliament mode.
I think for the styling and the sorting a new issue should be opened.

2024-12-16 15:18 UTC, bastianjoel approved these changes

2024-12-17 07:20 UTC, Elblinator approved these changes

2024-12-17 07:20 UTC, merged