Hide submitters dropbox in motion create if cannot see users
OpenSlides/openslides-client pull request #4484
Opened 2024-12-12 12:11 UTC by reiterl

Resolve #4457 

Needs:
https://github.com/OpenSlides/openslides-backend/issues/2760

2024-12-12 14:55 UTC, Elblinator requested changes
- Please change the  helpText: _(`Requires permission to manage motions`), to                         helpText: _(`Requires permission to manage motion metadata`)

- hide the new h3 "Submitters" if a person is not allowed to change meta data

2024-12-13 07:32 UTC, reiterl commented
Updated, new helptext of the meeting setting and changed the visibility of the submitters label.

2024-12-17 13:03 UTC, Elblinator approved these changes
function

2025-01-10 13:06 UTC, bastianjoel approved these changes

2025-01-10 13:06 UTC, merged