Fix wrong language after login
OpenSlides/openslides-client pull request #4489
Opened 2024-12-16 11:13 UTC by bastianjoel

resolves #4462 

This seems to improve the situation. But I am not entirely sure if it fully fixes it.

2024-12-17 12:46 UTC, Elblinator approved these changes
Code looks fine 
Cannot test functionality

2025-01-10 19:18 UTC, MSoeb requested changes
Talked about it with Bastian. Fix doesn't work as intended. Language still wrong at first login.

2025-01-13 16:30 UTC, luisa-beerboom approved these changes
Code LGTM

2025-01-15 07:32 UTC, MSoeb requested changes
Doesn't work. Problem still occurs. Tested with Chromium and Brave.

Additionally something strange appears in both browsers after opening the website: The CPU load rises and fan speed rises.

2025-01-15 12:38 UTC, MSoeb approved these changes
Looks good. Tested with Chrome, Brave and FF.

2025-01-15 12:38 UTC, merged