Add max per option validator and onkeyon for votes input fields
OpenSlides/openslides-client pull request #4492
Opened 2024-12-18 07:58 UTC by reiterl

Resolve #4453

2024-12-19 08:48 UTC, bastianjoel requested changes

2024-12-19 08:48 UTC, bastianjoel commented on client/src/app/infrastructure/utils/validators/is-number-range.ts
> +export function isNumberRange(minCtrlName: string, maxCtrlName: string, errorName: string): ValidatorFn {
Might be a good idea to set a default value for that. 

```suggestion
export function isNumberRange(minCtrlName: string, maxCtrlName: string, errorName: string = `rangeError`): ValidatorFn {
```

2024-12-19 09:54 UTC, bastianjoel approved these changes

2025-01-06 14:53 UTC, Elblinator requested changes
The min-votes are now in warn-colour if the two other amounts are wrong, they should not be in warn colour
![Screenshot_20250106_154204](https://github.com/user-attachments/assets/3538afb0-f4ab-4c2f-bd3f-313321ed3324)


If Yes as voting method was selected and then max per option is bigger max per vote and then another voting method is selected then you cannot save the balloot
![Screenshot_20250106_154107](https://github.com/user-attachments/assets/4173fd41-717a-4758-9427-5df440a0efcb)

2025-01-07 07:43 UTC, reiterl commented
As min-votes, max-votes and max-votes-per option is one form group it is not easy possible to have the validator on just two of the fields.

2025-01-07 12:10 UTC, Elblinator approved these changes
function

both described things are fixed

2025-01-10 12:50 UTC, bastianjoel approved these changes

2025-01-10 12:50 UTC, merged