Add pdf export of visible amendments in motion detail view
OpenSlides/openslides-client pull request #4493
Opened 2024-12-18 10:32 UTC by anbebe

Closes #4431

2024-12-19 08:45 UTC, bastianjoel requested changes

2024-12-19 08:45 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
> +        const changesToShow = changes.filter(change => change.showInDiffView() || showAllChanges);
```suggestion
        const changesToShow = showAllChanges ? changes : changes.filter(change => change.showInDiffView());
```

2024-12-19 08:45 UTC, bastianjoel commented on client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts
> +            showAllChanges: args.showAllChanges
This is not needed because `args` is already spread.
```suggestion
```

2025-01-07 10:52 UTC, Elblinator commented
Currently it is not completely WYSIWYG
@bspekker please state what the most wanted things are:
This is the motion in the diff version:
![Screenshot_20250107_114123](https://github.com/user-attachments/assets/687652a6-cace-46dd-a010-05f44a613b39)

This is the corresponding PDF:
![Screenshot_20250107_114341](https://github.com/user-attachments/assets/1daca738-8244-4b27-aed5-c8273138ced0)

This is the same motion in diff version and with "Show all change" activated
![Screenshot_20250107_114453](https://github.com/user-attachments/assets/e0ca36e8-49a5-4894-8784-3f3f587064aa)


Coresponding PDF:
![Screenshot_20250107_114509](https://github.com/user-attachments/assets/a50055d2-695a-497a-9fb4-c31e13e65d97)


As you can see...
If the checkbox is not ticked, then the amendments in the PDF have the title "Change recommendation" even though in the motion detail view they don't have this, and they are not change recommendations but amendments
If the checkbox is ticked, then the amendments have a different title "Change recommendation" and they are missing the number and the state.

Additional note: 
Change recommendations are currently always displayed in the diff version (even if they are rejected) given the WYSIWYG principles they should always be exported in the diff version. But should they have the title "Change recommendation", even though they do not have this title in the motion detail?

2025-01-07 12:19 UTC, bspekker commented
The PDF export should always include the number and status of visible amendments and the title "change recommendations" for change recommendations even when checkbox "show all changes" is not ticked. 

Rejected change recommendations should have the added label "rejected".

2025-01-09 11:12 UTC, bastianjoel approved these changes

2025-01-10 12:17 UTC, merged