Fix redirection to error page in meetings
OpenSlides/openslides-client pull request #663
Opened 2021-11-24 14:42 UTC by tsiegleauq

Fixes the redirection to the error handling page if a user accesses a
restricted page

fixes #626

2021-11-24 14:44 UTC, tsiegleauq commented
this is mose likely not the end of the line, but prevents some nasty infinity loops when trying to access restricted areas.

* The auth guard checks if OP can access, asks the "hasPerms", that would return false, then would link to the error page
* The error page would call canActivate, and since we are not in a meeting "hasPerms" would fail and link to the error page
* loop.

2021-11-25 14:30 UTC, emanuelschuetze requested changes
redirect for /users does not work correctly:

example
https://localhost:8000/5/users redirects to https://localhost:8000/ instead of https://localhost:8000/5

2021-11-30 16:40 UTC, tsiegleauq commented
Redirecting to the meeting error page works now in more cases
Accessing non existing routes will forward you to / in the most parts instead of assuming it might be a meeting id.

routes that appear to be a meeting ID are still interpreted as such.

2021-12-01 08:40 UTC, emanuelschuetze approved these changes

2021-12-01 08:40 UTC, merged