Adds the 'poll_backend' key to the poll-form
OpenSlides/openslides-client pull request #668
Opened 2021-11-26 10:47 UTC by GabrielInTheWorld

Fixes #655

Hint: The card for one assignment-poll could be adjusted so, that the poll_backend type can be read.

2021-11-30 14:52 UTC, tsiegleauq approved these changes
OK, not tested

2021-12-01 08:35 UTC, GabrielInTheWorld commented
Label: "Poll duration"

- [ ] "Short" or "Long" poll
- [ ] Add the label to a poll-detail card

2021-12-03 11:27 UTC, emanuelschuetze requested changes
Retested. 
* I cannot change the poll backend in poll update dialog!
* please use in poll detail view the same label as in poll form (short/long poll, not fast/long)
* wish: please add the meta infomation of a motion poll also in the mat-card in motion detail view (as we do it already in assignment poll mat-card in assigment-detail-view)

2021-12-03 12:48 UTC, emanuelschuetze approved these changes

2021-12-03 12:48 UTC, merged