Spaces group views
OpenSlides/openslides-client pull request #819
Opened 2022-02-09 11:11 UTC by bug0001

unwanted spaces issue

2022-02-10 09:56 UTC, jsangmeister commented
Please always fill out the correct meta information, see https://github.com/OpenSlides/OpenSlides/wiki/Guideline-for-Issues-and-Pull-Requests

2022-02-10 15:21 UTC, GabrielInTheWorld commented on client/src/app/site/users/components/user-list/user-list.component.html
>                  </os-icon-container>
That is good, but you're missing some other places described in #799.

2022-02-11 10:18 UTC, bug0001 commented
Please specify in which area of the application "In the list of submitters, there is a space after the username of a submitter" takes place.

2022-02-11 11:45 UTC, GabrielInTheWorld requested changes

2022-02-11 11:45 UTC, GabrielInTheWorld commented on client/src/app/site/users/components/user-list/user-list.component.html
> +                    <span *ngFor="let group of getUserGroups(user); let last = last" class="remove-spaces-group">
You have to adjust the class here to your new class-name.

2022-02-11 14:01 UTC, GabrielInTheWorld approved these changes
Rebase and ensure, that the tests run successfully.

2022-02-14 08:08 UTC, merged