Can set voteweight to null
OpenSlides/openslides-client pull request #883
Opened 2022-02-25 11:54 UTC by GabrielInTheWorld

Fixes #882.

Waits for OpenSlides/openslides-backend#1242.

2022-06-29 12:20 UTC, emanuelschuetze requested changes
Set voteweight for user to '0'. Save user form. Reopen user form => field 'voteweight' is not visible!

2022-08-12 07:58 UTC, bastianjoel requested changes
I think shared/utils/to-decimal.ts is not needed. The functions are already defined in infrastructure/utils/functions.ts

2022-08-12 12:01 UTC, bastianjoel approved these changes

2022-08-16 10:57 UTC, MSoeb approved these changes

2022-08-16 11:18 UTC, merged