Some improvements for motion states
OpenSlides/openslides-client pull request #994
Opened 2022-04-16 20:39 UTC by GabrielInTheWorld

- "Created timestamp" depends on a motion state (Fixes #982)
- A motion can only be forwarded if it is in the correct motion state (Fixes #981)

2022-04-18 21:40 UTC, emanuelschuetze requested changes
* timestamp is not recreated/updated if timestamp already exists (e.g. set two checkboxes for two states -> first time works, second state not)
* forwording state check is not working -> forwarding is possible in each state

2022-04-19 06:01 UTC, jsangmeister commented
> * timestamp is not recreated/updated if timestamp already exists (e.g. set two checkboxes for two states -> first time works, second state not)

This is intended and what we discussed - only the first state should set the timestamp, or else it becomes meaningless and more of an "updated" timestamp.

2022-04-19 06:08 UTC, jsangmeister commented
> * forwording state check is not working -> forwarding is possible in each state

This is not yet implemented in the backend and will follow with the whole rework in https://github.com/OpenSlides/openslides-backend/pull/1296. The client should, however, probably hide the button if forwarding is not possible.

2022-04-19 07:39 UTC, emanuelschuetze approved these changes

2022-04-19 08:22 UTC, merged